// Code generated by tools/gen; DO NOT EDIT.
package sdk

import "context"

// Song URL, theme, and top-list models share this shard.
type SongUrlRequest struct {
	AlbumAudioId int               `json:"album_audio_id,omitempty"`
	AlbumId      int               `json:"album_id,omitempty"`
	FreePart     bool              `json:"free_part,omitempty"`
	Hash         string            `json:"hash,omitempty"`
	Quality      any               `json:"quality,omitempty"`
	Cookie       map[string]string `json:"-"`
	Extra        map[string]any    `json:"-"`
}

type SongUrlResponse = Response

func (c *Client) SongUrl(ctx context.Context, req SongUrlRequest) (*SongUrlResponse, error) {
	params := structToMap(req)
	delete(params, "Cookie")
	delete(params, "Extra")
	if compat, ok := buildCompatParams("song_url", params, req.Cookie); ok {
		params = compat
	}
	for k, v := range req.Extra {
		params[k] = v
	}
	cookie := applyCompatCookie("song_url", req.Cookie)
	resp, err := c.Call(ctx, RouteSongUrl, Request{Params: params, Cookie: cookie})
	if err != nil {
		return nil, err
	}
	out := SongUrlResponse(*resp)
	return &out, nil
}

type SongUrlNewRequest struct {
	AlbumAudioId any               `json:"album_audio_id,omitempty"`
	Dfid         any               `json:"dfid,omitempty"`
	FreePart     bool              `json:"free_part,omitempty"`
	Hash         any               `json:"hash,omitempty"`
	Quality      any               `json:"quality,omitempty"`
	Token        any               `json:"token,omitempty"`
	Userid       int               `json:"userid,omitempty"`
	VipType      int               `json:"vipType,omitempty"`
	VipToken     any               `json:"vip_token,omitempty"`
	Cookie       map[string]string `json:"-"`
	Extra        map[string]any    `json:"-"`
}

type SongUrlNewResponse = Response

func (c *Client) SongUrlNew(ctx context.Context, req SongUrlNewRequest) (*SongUrlNewResponse, error) {
	params := structToMap(req)
	delete(params, "Cookie")
	delete(params, "Extra")
	if compat, ok := buildCompatParams("song_url_new", params, req.Cookie); ok {
		params = compat
	}
	for k, v := range req.Extra {
		params[k] = v
	}
	cookie := applyCompatCookie("song_url_new", req.Cookie)
	resp, err := c.Call(ctx, RouteSongUrlNew, Request{Params: params, Cookie: cookie})
	if err != nil {
		return nil, err
	}
	out := SongUrlNewResponse(*resp)
	return &out, nil
}

type ThemeMusicRequest struct {
	Ids    any               `json:"ids,omitempty"`
	Userid any               `json:"userid,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type ThemeMusicResponse = Response

type ThemeMusicDetailRequest struct {
	Id     any               `json:"id,omitempty"`
	Userid any               `json:"userid,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type ThemeMusicDetailResponse = Response

type ThemePlaylistRequest struct {
	Userid any               `json:"userid,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type ThemePlaylistResponse = Response

type ThemePlaylistTrackRequest struct {
	ThemeId any               `json:"theme_id,omitempty"`
	Userid  any               `json:"userid,omitempty"`
	Cookie  map[string]string `json:"-"`
	Extra   map[string]any    `json:"-"`
}

type ThemePlaylistTrackResponse = Response

type TopAlbumRequest struct {
	Page     int               `json:"page,omitempty"`
	Pagesize int               `json:"pagesize,omitempty"`
	Token    any               `json:"token,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type TopAlbumResponse = Response

func (c *Client) TopAlbum(ctx context.Context, req TopAlbumRequest) (*TopAlbumResponse, error) {
	params := structToMap(req)
	delete(params, "Cookie")
	delete(params, "Extra")
	if compat, ok := buildCompatParams("top_album", params, req.Cookie); ok {
		params = compat
	}
	for k, v := range req.Extra {
		params[k] = v
	}
	cookie := applyCompatCookie("top_album", req.Cookie)
	resp, err := c.Call(ctx, RouteTopAlbum, Request{Params: params, Cookie: cookie})
	if err != nil {
		return nil, err
	}
	out := TopAlbumResponse(*resp)
	return &out, nil
}

type TopCardRequest struct {
	CardId int               `json:"card_id,omitempty"`
	Dfid   any               `json:"dfid,omitempty"`
	Userid any               `json:"userid,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type TopCardResponse = Response

type TopCardYouthRequest struct {
	CardId   int               `json:"card_id,omitempty"`
	Pagesize any               `json:"pagesize,omitempty"`
	Tagid    any               `json:"tagid,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type TopCardYouthResponse = Response

type TopIpRequest struct {
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type TopIpResponse = Response

type TopPlaylistRequest struct {
	CategoryId int               `json:"category_id,omitempty"`
	ModuleId   int               `json:"module_id,omitempty"`
	Page       int               `json:"page,omitempty"`
	Pagesize   int               `json:"pagesize,omitempty"`
	Sort       int               `json:"sort,omitempty"`
	Userid     any               `json:"userid,omitempty"`
	Withsong   int               `json:"withsong,omitempty"`
	Withtag    int               `json:"withtag,omitempty"`
	Cookie     map[string]string `json:"-"`
	Extra      map[string]any    `json:"-"`
}

type TopPlaylistResponse = Response

type TopSongRequest struct {
	Page     int               `json:"page,omitempty"`
	Pagesize int               `json:"pagesize,omitempty"`
	Type     int               `json:"type,omitempty"`
	Userid   any               `json:"userid,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type TopSongResponse = Response
