// Code generated by tools/gen; DO NOT EDIT.
package sdk

import "context"

// Lookup and login-adjacent models are grouped together.
type ImagesAudioRequest struct {
	AlbumAudioId string            `json:"album_audio_id,omitempty"`
	AudioId      string            `json:"audio_id,omitempty"`
	Count        int               `json:"count,omitempty"`
	Filename     string            `json:"filename,omitempty"`
	Hash         string            `json:"hash,omitempty"`
	Cookie       map[string]string `json:"-"`
	Extra        map[string]any    `json:"-"`
}

type ImagesAudioResponse = Response

func (c *Client) ImagesAudio(ctx context.Context, req ImagesAudioRequest) (*ImagesAudioResponse, error) {
	params := structToMap(req)
	delete(params, "Cookie")
	delete(params, "Extra")
	if compat, ok := buildCompatParams("images_audio", params, req.Cookie); ok {
		params = compat
	}
	for k, v := range req.Extra {
		params[k] = v
	}
	cookie := applyCompatCookie("images_audio", req.Cookie)
	resp, err := c.Call(ctx, RouteImagesAudio, Request{Params: params, Cookie: cookie})
	if err != nil {
		return nil, err
	}
	out := ImagesAudioResponse(*resp)
	return &out, nil
}

type IpRequest struct {
	Id       any               `json:"id,omitempty"`
	Page     int               `json:"page,omitempty"`
	Pagesize int               `json:"pagesize,omitempty"`
	Type     any               `json:"type,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type IpResponse = Response

func (c *Client) Ip(ctx context.Context, req IpRequest) (*IpResponse, error) {
	params := structToMap(req)
	delete(params, "Cookie")
	delete(params, "Extra")
	if compat, ok := buildCompatParams("ip", params, req.Cookie); ok {
		params = compat
	}
	for k, v := range req.Extra {
		params[k] = v
	}
	cookie := applyCompatCookie("ip", req.Cookie)
	resp, err := c.Call(ctx, RouteIp, Request{Params: params, Cookie: cookie})
	if err != nil {
		return nil, err
	}
	out := IpResponse(*resp)
	return &out, nil
}

type IpDateilRequest struct {
	Id     string            `json:"id,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type IpDateilResponse = Response

func (c *Client) IpDateil(ctx context.Context, req IpDateilRequest) (*IpDateilResponse, error) {
	params := structToMap(req)
	delete(params, "Cookie")
	delete(params, "Extra")
	if compat, ok := buildCompatParams("ip_dateil", params, req.Cookie); ok {
		params = compat
	}
	for k, v := range req.Extra {
		params[k] = v
	}
	cookie := applyCompatCookie("ip_dateil", req.Cookie)
	resp, err := c.Call(ctx, RouteIpDateil, Request{Params: params, Cookie: cookie})
	if err != nil {
		return nil, err
	}
	out := IpDateilResponse(*resp)
	return &out, nil
}

type IpPlaylistRequest struct {
	Id       any               `json:"id,omitempty"`
	Page     int               `json:"page,omitempty"`
	Pagesize int               `json:"pagesize,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type IpPlaylistResponse = Response

func (c *Client) IpPlaylist(ctx context.Context, req IpPlaylistRequest) (*IpPlaylistResponse, error) {
	params := structToMap(req)
	delete(params, "Cookie")
	delete(params, "Extra")
	if compat, ok := buildCompatParams("ip_playlist", params, req.Cookie); ok {
		params = compat
	}
	for k, v := range req.Extra {
		params[k] = v
	}
	cookie := applyCompatCookie("ip_playlist", req.Cookie)
	resp, err := c.Call(ctx, RouteIpPlaylist, Request{Params: params, Cookie: cookie})
	if err != nil {
		return nil, err
	}
	out := IpPlaylistResponse(*resp)
	return &out, nil
}

type IpZoneRequest struct {
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type IpZoneResponse = Response

type IpZoneHomeRequest struct {
	Id     any               `json:"id,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type IpZoneHomeResponse = Response

func (c *Client) IpZoneHome(ctx context.Context, req IpZoneHomeRequest) (*IpZoneHomeResponse, error) {
	params := structToMap(req)
	delete(params, "Cookie")
	delete(params, "Extra")
	if compat, ok := buildCompatParams("ip_zone_home", params, req.Cookie); ok {
		params = compat
	}
	for k, v := range req.Extra {
		params[k] = v
	}
	cookie := applyCompatCookie("ip_zone_home", req.Cookie)
	resp, err := c.Call(ctx, RouteIpZoneHome, Request{Params: params, Cookie: cookie})
	if err != nil {
		return nil, err
	}
	out := IpZoneHomeResponse(*resp)
	return &out, nil
}

type KmrAudioMvRequest struct {
	AlbumAudioId string            `json:"album_audio_id,omitempty"`
	Fields       any               `json:"fields,omitempty"`
	Cookie       map[string]string `json:"-"`
	Extra        map[string]any    `json:"-"`
}

type KmrAudioMvResponse = Response

type KrmAudioRequest struct {
	AlbumAudioId string            `json:"album_audio_id,omitempty"`
	Fields       any               `json:"fields,omitempty"`
	Cookie       map[string]string `json:"-"`
	Extra        map[string]any    `json:"-"`
}

type KrmAudioResponse = Response

type LastestSongsListenRequest struct {
	Pagesize int               `json:"pagesize,omitempty"`
	Token    any               `json:"token,omitempty"`
	Userid   int               `json:"userid,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type LastestSongsListenResponse = Response
