// Code generated by tools/gen; DO NOT EDIT.
package sdk

import "context"

// User, video, and youth models stay together in the final shard.
type UserCloudRequest struct {
	Page     any               `json:"page,omitempty"`
	Pagesize any               `json:"pagesize,omitempty"`
	Token    any               `json:"token,omitempty"`
	Userid   any               `json:"userid,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type UserCloudResponse = Response

type UserCloudUrlRequest struct {
	AlbumAudioId any               `json:"album_audio_id,omitempty"`
	AudioId      any               `json:"audio_id,omitempty"`
	Hash         any               `json:"hash,omitempty"`
	Name         any               `json:"name,omitempty"`
	Cookie       map[string]string `json:"-"`
	Extra        map[string]any    `json:"-"`
}

type UserCloudUrlResponse = Response

type UserDetailRequest struct {
	Token  any               `json:"token,omitempty"`
	Userid int               `json:"userid,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type UserDetailResponse = Response

type UserFollowRequest struct {
	Token  any               `json:"token,omitempty"`
	Userid any               `json:"userid,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type UserFollowResponse = Response

type UserHistoryRequest struct {
	Bp     any               `json:"bp,omitempty"`
	Token  any               `json:"token,omitempty"`
	Userid any               `json:"userid,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type UserHistoryResponse = Response

type UserListenRequest struct {
	Token  any               `json:"token,omitempty"`
	Type   any               `json:"type,omitempty"`
	Userid any               `json:"userid,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type UserListenResponse = Response

type UserPlaylistRequest struct {
	Page     int               `json:"page,omitempty"`
	Pagesize int               `json:"pagesize,omitempty"`
	Token    string            `json:"token,omitempty"`
	Userid   int               `json:"userid,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type UserPlaylistResponse = Response

func (c *Client) UserPlaylist(ctx context.Context, req UserPlaylistRequest) (*UserPlaylistResponse, error) {
	params := structToMap(req)
	delete(params, "Cookie")
	delete(params, "Extra")
	if compat, ok := buildCompatParams("user_playlist", params, req.Cookie); ok {
		params = compat
	}
	for k, v := range req.Extra {
		params[k] = v
	}
	cookie := applyCompatCookie("user_playlist", req.Cookie)
	resp, err := c.Call(ctx, RouteUserPlaylist, Request{Params: params, Cookie: cookie})
	if err != nil {
		return nil, err
	}
	out := UserPlaylistResponse(*resp)
	return &out, nil
}

type UserVideoCollectRequest struct {
	Page     any               `json:"page,omitempty"`
	Pagesize any               `json:"pagesize,omitempty"`
	Token    any               `json:"token,omitempty"`
	Userid   any               `json:"userid,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type UserVideoCollectResponse = Response

type UserVideoLoveRequest struct {
	Pagesize any               `json:"pagesize,omitempty"`
	Userid   any               `json:"userid,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type UserVideoLoveResponse = Response

type UserVipDetailRequest struct {
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type UserVipDetailResponse = Response

type VideoDetailRequest struct {
	Id     any               `json:"id,omitempty"`
	Token  any               `json:"token,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type VideoDetailResponse = Response

type VideoPrivilegeRequest struct {
	Hash   string            `json:"hash,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type VideoPrivilegeResponse = Response

type VideoUrlRequest struct {
	Hash   any               `json:"hash,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type VideoUrlResponse = Response

type YouthChannelAllRequest struct {
	Page     any               `json:"page,omitempty"`
	Pagesize any               `json:"pagesize,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type YouthChannelAllResponse = Response

type YouthChannelAmwayRequest struct {
	GlobalCollectionId any               `json:"global_collection_id,omitempty"`
	Cookie             map[string]string `json:"-"`
	Extra              map[string]any    `json:"-"`
}

type YouthChannelAmwayResponse = Response

type YouthChannelDetailRequest struct {
	GlobalCollectionId any               `json:"global_collection_id,omitempty"`
	Cookie             map[string]string `json:"-"`
	Extra              map[string]any    `json:"-"`
}

type YouthChannelDetailResponse = Response

type YouthChannelSimilarRequest struct {
	ChannelId any               `json:"channel_id,omitempty"`
	VipType   any               `json:"vip_type,omitempty"`
	Cookie    map[string]string `json:"-"`
	Extra     map[string]any    `json:"-"`
}

type YouthChannelSimilarResponse = Response

type YouthChannelSongRequest struct {
	GlobalCollectionId any               `json:"global_collection_id,omitempty"`
	Page               any               `json:"page,omitempty"`
	Pagesize           any               `json:"pagesize,omitempty"`
	Cookie             map[string]string `json:"-"`
	Extra              map[string]any    `json:"-"`
}

type YouthChannelSongResponse = Response

type YouthChannelSongDetailRequest struct {
	Fileid             any               `json:"fileid,omitempty"`
	GlobalCollectionId any               `json:"global_collection_id,omitempty"`
	Cookie             map[string]string `json:"-"`
	Extra              map[string]any    `json:"-"`
}

type YouthChannelSongDetailResponse = Response

type YouthChannelSubRequest struct {
	GlobalCollectionId any               `json:"global_collection_id,omitempty"`
	T                  int               `json:"t,omitempty"`
	Cookie             map[string]string `json:"-"`
	Extra              map[string]any    `json:"-"`
}

type YouthChannelSubResponse = Response

type YouthDayVipRequest struct {
	ReceiveDay any               `json:"receive_day,omitempty"`
	Cookie     map[string]string `json:"-"`
	Extra      map[string]any    `json:"-"`
}

type YouthDayVipResponse = Response

type YouthDayVipUpgradeRequest struct {
	Userid int               `json:"userid,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type YouthDayVipUpgradeResponse = Response

type YouthDynamicRequest struct {
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type YouthDynamicResponse = Response

type YouthDynamicRecentRequest struct {
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type YouthDynamicRecentResponse = Response

type YouthListenSongRequest struct {
	Mixsongid int               `json:"mixsongid,omitempty"`
	Cookie    map[string]string `json:"-"`
	Extra     map[string]any    `json:"-"`
}

type YouthListenSongResponse = Response

type YouthMonthVipRecordRequest struct {
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type YouthMonthVipRecordResponse = Response

type YouthUnionVipRequest struct {
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type YouthUnionVipResponse = Response

type YouthUserSongRequest struct {
	Page     any               `json:"page,omitempty"`
	Pagesize any               `json:"pagesize,omitempty"`
	Type     int               `json:"type,omitempty"`
	Userid   any               `json:"userid,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type YouthUserSongResponse = Response

type YouthVipRequest struct {
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type YouthVipResponse = Response
