// Code generated by tools/gen; DO NOT EDIT.
package sdk

import (
	"fmt"
	"strconv"
)

func buildCompatParams(identifier string, in map[string]any, cookie map[string]string) (map[string]any, bool) {
	if out, ok := buildCompatParamsGroupA(identifier, in, cookie); ok {
		return out, true
	}
	if out, ok := buildCompatParamsGroupB(identifier, in, cookie); ok {
		return out, true
	}
	if out, ok := buildCompatParamsGroupC(identifier, in, cookie); ok {
		return out, true
	}
	if out, ok := buildCompatParamsGroupD(identifier, in, cookie); ok {
		return out, true
	}
	if out, ok := buildCompatParamsGroupE(identifier, in, cookie); ok {
		return out, true
	}
	return in, false
}

func applyCompatCookie(identifier string, cookie map[string]string) map[string]string {
	out := map[string]string{}
	for k, v := range cookie {
		out[k] = v
	}
	switch identifier {
	case "captcha_sent":
		if v := cookie["KUGOU_API_MID"]; v != "" {
			out["mid"] = v
		}
	}
	return out
}

func compatFirstAny(v ...any) any {
	for _, x := range v {
		switch vv := x.(type) {
		case nil:
			continue
		case string:
			if vv != "" {
				return vv
			}
		default:
			return x
		}
	}
	return nil
}

func compatFirstAnyString(v any, def string) string {
	if v == nil {
		return def
	}
	s := fmt.Sprintf("%v", v)
	if s == "" || s == "<nil>" {
		return def
	}
	return s
}

func compatFirstAnyInt(v any, def int) int {
	if v == nil {
		return def
	}
	s := fmt.Sprintf("%v", v)
	if s == "" || s == "<nil>" {
		return def
	}
	n, err := strconv.Atoi(s)
	if err != nil || n == 0 {
		return def
	}
	return n
}

func compatDefaultLiteral(kind string, s string, i int, bval bool) any {
	switch kind {
	case "string":
		return s
	case "int":
		return i
	case "bool":
		return bval
	default:
		return nil
	}
}
