// Code generated by tools/gen; DO NOT EDIT.
package sdk

func buildCompatParamsGroupC(identifier string, in map[string]any, cookie map[string]string) (map[string]any, bool) {
	switch identifier {
	case "personal_fm":
		out := map[string]any{}
		out["mid"] = cookie["KUGOU_API_MID"]
		out["action"] = compatFirstAnyString(in["action"], "play")
		out["recommend_source_locked"] = 0
		out["callerid"] = 0
		out["m_type"] = 1
		out["platform"] = compatFirstAnyString(in["platform"], "ios")
		out["area_code"] = 1
		out["mode"] = compatFirstAnyString(in["mode"], "normal")
		out["fakem"] = "ca981cfc583a4c37f28d2d49000013c16a0a"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "playhistory_upload":
		out := map[string]any{}
		out["url"] = "/playhistory/v1/upload_songs"
		out["encryptType"] = "android"
		out["method"] = "POST"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "playlist_add":
		out := map[string]any{}
		out["total_ver"] = 0
		out["is_pri"] = 0
		out["from_shupinmv"] = 0
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "playlist_del":
		out := map[string]any{}
		out["total_ver"] = 0
		out["type"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "playlist_detail":
		out := map[string]any{}
		out["userid"] = compatFirstAny(in["userid"], cookie["userid"], compatDefaultLiteral("int", "", 0, false))
		out["token"] = compatFirstAny(in["token"], cookie["token"], compatDefaultLiteral("string", "", 0, false))
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "playlist_effect":
		out := map[string]any{}
		out["page"] = compatFirstAnyInt(in["page"], 1)
		out["pagesize"] = compatFirstAnyInt(in["pagesize"], 30)
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "playlist_similar":
		out := map[string]any{}
		out["userid"] = compatFirstAny(in["userid"], cookie["userid"], compatDefaultLiteral("int", "", 0, false))
		out["ugc"] = 1
		out["show_list"] = 1
		out["need_songs"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "playlist_tags":
		out := map[string]any{}
		out["tag_type"] = "collection"
		out["tag_id"] = 0
		out["source"] = 3
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "playlist_track_all":
		out := map[string]any{}
		out["area_code"] = 1
		out["plat"] = 1
		out["type"] = 1
		out["mode"] = 1
		out["personal_switch"] = 1
		out["extend_fields"] = "abtags,hot_cmt,popularization"
		out["global_collection_id"] = in["id"]
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "playlist_track_all_new":
		out := map[string]any{}
		out["area_code"] = 1
		out["show_relate_goods"] = 0
		out["allplatform"] = 1
		out["show_cover"] = 1
		out["type"] = 0
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "playlist_tracks_add":
		out := map[string]any{}
		out["list_ver"] = 0
		out["type"] = 0
		out["slow_upload"] = 1
		out["scene"] = "false;null"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "playlist_tracks_del":
		out := map[string]any{}
		out["type"] = 0
		out["list_ver"] = 0
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "privilege_lite":
		out := map[string]any{}
		out["area_code"] = 1
		out["behavior"] = "play"
		out["need_hash_offset"] = 1
		out["relate"] = 1
		out["support_verify"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "rank_audio":
		out := map[string]any{}
		out["show_portrait_mv"] = 1
		out["show_type_total"] = 1
		out["filter_original_remarks"] = 1
		out["area_code"] = 1
		out["type"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "recommend_songs":
		out := map[string]any{}
		out["platform"] = compatFirstAnyString(in["platform"], "android")
		out["userid"] = compatFirstAny(in["userid"], cookie["userid"], compatDefaultLiteral("string", "0", 0, false))
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "search":
		out := map[string]any{}
		out["albumhide"] = 0
		out["iscorrection"] = 1
		out["keyword"] = compatFirstAnyString(in["keywords"], "")
		out["nocollect"] = 0
		out["page"] = compatFirstAnyInt(in["page"], 1)
		out["pagesize"] = compatFirstAnyInt(in["pagesize"], 30)
		out["platform"] = "AndroidFilter"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "search_complex":
		out := map[string]any{}
		out["platform"] = "AndroidFilter"
		out["page"] = compatFirstAnyInt(in["page"], 1)
		out["pagesize"] = compatFirstAnyInt(in["pagesize"], 30)
		out["cursor"] = 0
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "search_default":
		out := map[string]any{}
		out["plat"] = 0
		out["tags"] = "{}"
		out["m_type"] = 0
		out["ability"] = "3"
		out["bitmap"] = 2
		out["mode"] = "normal"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "search_hot":
		out := map[string]any{}
		out["navid"] = 1
		out["plat"] = 2
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "search_lyric":
		out := map[string]any{}
		out["album_audio_id"] = compatFirstAnyInt(in["album_audio_id"], 0)
		out["duration"] = 0
		out["hash"] = compatFirstAnyString(in["hash"], "")
		out["keyword"] = compatFirstAnyString(in["keywords"], "")
		out["lrctxt"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	default:
		return nil, false
	}
}
