// Code generated by tools/gen; DO NOT EDIT.
package sdk

import "context"

// Personal FM and playlist models are grouped together.
type PersonalFmRequest struct {
	Action        string            `json:"action,omitempty"`
	Hash          any               `json:"hash,omitempty"`
	IsOverplay    bool              `json:"is_overplay,omitempty"`
	Mode          string            `json:"mode,omitempty"`
	Platform      string            `json:"platform,omitempty"`
	Playtime      any               `json:"playtime,omitempty"`
	RemainSongcnt int               `json:"remain_songcnt,omitempty"`
	SongPoolId    int               `json:"song_pool_id,omitempty"`
	Songid        any               `json:"songid,omitempty"`
	Token         int               `json:"token,omitempty"`
	Userid        int               `json:"userid,omitempty"`
	VipType       int               `json:"vipType,omitempty"`
	Cookie        map[string]string `json:"-"`
	Extra         map[string]any    `json:"-"`
}

type PersonalFmResponse = Response

type PlayhistoryUploadRequest struct {
	Mxid   int               `json:"mxid,omitempty"`
	Pc     int               `json:"pc,omitempty"`
	Time   int               `json:"time,omitempty"`
	Token  any               `json:"token,omitempty"`
	Userid any               `json:"userid,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type PlayhistoryUploadResponse = Response

type PlaylistAddRequest struct {
	IsPri            any               `json:"is_pri,omitempty"`
	ListCreateGid    any               `json:"list_create_gid,omitempty"`
	ListCreateListid any               `json:"list_create_listid,omitempty"`
	ListCreateUserid any               `json:"list_create_userid,omitempty"`
	Name             any               `json:"name,omitempty"`
	Source           any               `json:"source,omitempty"`
	Token            any               `json:"token,omitempty"`
	Type             any               `json:"type,omitempty"`
	Userid           any               `json:"userid,omitempty"`
	Cookie           map[string]string `json:"-"`
	Extra            map[string]any    `json:"-"`
}

type PlaylistAddResponse = Response

type PlaylistDelRequest struct {
	Listid int               `json:"listid,omitempty"`
	Token  any               `json:"token,omitempty"`
	Userid any               `json:"userid,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type PlaylistDelResponse = Response

type PlaylistDetailRequest struct {
	Ids    string            `json:"ids,omitempty"`
	Token  any               `json:"token,omitempty"`
	Userid any               `json:"userid,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type PlaylistDetailResponse = Response

func (c *Client) PlaylistDetail(ctx context.Context, req PlaylistDetailRequest) (*PlaylistDetailResponse, error) {
	params := structToMap(req)
	delete(params, "Cookie")
	delete(params, "Extra")
	if compat, ok := buildCompatParams("playlist_detail", params, req.Cookie); ok {
		params = compat
	}
	for k, v := range req.Extra {
		params[k] = v
	}
	cookie := applyCompatCookie("playlist_detail", req.Cookie)
	resp, err := c.Call(ctx, RoutePlaylistDetail, Request{Params: params, Cookie: cookie})
	if err != nil {
		return nil, err
	}
	out := PlaylistDetailResponse(*resp)
	return &out, nil
}

type PlaylistEffectRequest struct {
	Page     int               `json:"page,omitempty"`
	Pagesize int               `json:"pagesize,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type PlaylistEffectResponse = Response

func (c *Client) PlaylistEffect(ctx context.Context, req PlaylistEffectRequest) (*PlaylistEffectResponse, error) {
	params := structToMap(req)
	delete(params, "Cookie")
	delete(params, "Extra")
	if compat, ok := buildCompatParams("playlist_effect", params, req.Cookie); ok {
		params = compat
	}
	for k, v := range req.Extra {
		params[k] = v
	}
	cookie := applyCompatCookie("playlist_effect", req.Cookie)
	resp, err := c.Call(ctx, RoutePlaylistEffect, Request{Params: params, Cookie: cookie})
	if err != nil {
		return nil, err
	}
	out := PlaylistEffectResponse(*resp)
	return &out, nil
}

type PlaylistSimilarRequest struct {
	Ids    string            `json:"ids,omitempty"`
	Userid any               `json:"userid,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type PlaylistSimilarResponse = Response

type PlaylistTagsRequest struct {
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type PlaylistTagsResponse = Response

func (c *Client) PlaylistTags(ctx context.Context, req PlaylistTagsRequest) (*PlaylistTagsResponse, error) {
	params := structToMap(req)
	delete(params, "Cookie")
	delete(params, "Extra")
	if compat, ok := buildCompatParams("playlist_tags", params, req.Cookie); ok {
		params = compat
	}
	for k, v := range req.Extra {
		params[k] = v
	}
	cookie := applyCompatCookie("playlist_tags", req.Cookie)
	resp, err := c.Call(ctx, RoutePlaylistTags, Request{Params: params, Cookie: cookie})
	if err != nil {
		return nil, err
	}
	out := PlaylistTagsResponse(*resp)
	return &out, nil
}

type PlaylistTrackAllRequest struct {
	Id       any               `json:"id,omitempty"`
	Page     int               `json:"page,omitempty"`
	Pagesize int               `json:"pagesize,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type PlaylistTrackAllResponse = Response

type PlaylistTrackAllNewRequest struct {
	Listid   any               `json:"listid,omitempty"`
	Page     any               `json:"page,omitempty"`
	Pagesize any               `json:"pagesize,omitempty"`
	Token    any               `json:"token,omitempty"`
	Userid   any               `json:"userid,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type PlaylistTrackAllNewResponse = Response

type PlaylistTracksAddRequest struct {
	Data   any               `json:"data,omitempty"`
	Listid any               `json:"listid,omitempty"`
	Token  any               `json:"token,omitempty"`
	Userid any               `json:"userid,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type PlaylistTracksAddResponse = Response

type PlaylistTracksDelRequest struct {
	Fileids any               `json:"fileids,omitempty"`
	Listid  any               `json:"listid,omitempty"`
	Token   any               `json:"token,omitempty"`
	Userid  any               `json:"userid,omitempty"`
	Cookie  map[string]string `json:"-"`
	Extra   map[string]any    `json:"-"`
}

type PlaylistTracksDelResponse = Response

type PrivilegeLiteRequest struct {
	AlbumId string            `json:"album_id,omitempty"`
	Hash    string            `json:"hash,omitempty"`
	Cookie  map[string]string `json:"-"`
	Extra   map[string]any    `json:"-"`
}

type PrivilegeLiteResponse = Response
