// Code generated by tools/gen; DO NOT EDIT.
package sdk

import "context"

// Late login models, lyric models, and PC radio models share this shard.
type LoginQrKeyRequest struct {
	Type   any               `json:"type,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type LoginQrKeyResponse = Response

func (c *Client) LoginQrKey(ctx context.Context, req LoginQrKeyRequest) (*LoginQrKeyResponse, error) {
	params := structToMap(req)
	delete(params, "Cookie")
	delete(params, "Extra")
	if compat, ok := buildCompatParams("login_qr_key", params, req.Cookie); ok {
		params = compat
	}
	for k, v := range req.Extra {
		params[k] = v
	}
	cookie := applyCompatCookie("login_qr_key", req.Cookie)
	resp, err := c.Call(ctx, RouteLoginQrKey, Request{Params: params, Cookie: cookie})
	if err != nil {
		return nil, err
	}
	out := LoginQrKeyResponse(*resp)
	return &out, nil
}

type LoginTokenRequest struct {
	Token  any               `json:"token,omitempty"`
	Userid any               `json:"userid,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type LoginTokenResponse = Response

func (c *Client) LoginToken(ctx context.Context, req LoginTokenRequest) (*LoginTokenResponse, error) {
	params := structToMap(req)
	delete(params, "Cookie")
	delete(params, "Extra")
	if compat, ok := buildCompatParams("login_token", params, req.Cookie); ok {
		params = compat
	}
	for k, v := range req.Extra {
		params[k] = v
	}
	cookie := applyCompatCookie("login_token", req.Cookie)
	resp, err := c.Call(ctx, RouteLoginToken, Request{Params: params, Cookie: cookie})
	if err != nil {
		return nil, err
	}
	out := LoginTokenResponse(*resp)
	return &out, nil
}

type LoginWxCheckRequest struct {
	Uuid   string            `json:"uuid,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type LoginWxCheckResponse = Response

func (c *Client) LoginWxCheck(ctx context.Context, req LoginWxCheckRequest) (*LoginWxCheckResponse, error) {
	params := structToMap(req)
	delete(params, "Cookie")
	delete(params, "Extra")
	if compat, ok := buildCompatParams("login_wx_check", params, req.Cookie); ok {
		params = compat
	}
	for k, v := range req.Extra {
		params[k] = v
	}
	cookie := applyCompatCookie("login_wx_check", req.Cookie)
	resp, err := c.Call(ctx, RouteLoginWxCheck, Request{Params: params, Cookie: cookie})
	if err != nil {
		return nil, err
	}
	out := LoginWxCheckResponse(*resp)
	return &out, nil
}

type LoginWxCreateRequest struct {
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type LoginWxCreateResponse = Response

func (c *Client) LoginWxCreate(ctx context.Context, req LoginWxCreateRequest) (*LoginWxCreateResponse, error) {
	params := structToMap(req)
	delete(params, "Cookie")
	delete(params, "Extra")
	if compat, ok := buildCompatParams("login_wx_create", params, req.Cookie); ok {
		params = compat
	}
	for k, v := range req.Extra {
		params[k] = v
	}
	cookie := applyCompatCookie("login_wx_create", req.Cookie)
	resp, err := c.Call(ctx, RouteLoginWxCreate, Request{Params: params, Cookie: cookie})
	if err != nil {
		return nil, err
	}
	out := LoginWxCreateResponse(*resp)
	return &out, nil
}

type LongaudioAlbumAudiosRequest struct {
	AlbumId  any               `json:"album_id,omitempty"`
	Page     any               `json:"page,omitempty"`
	Pagesize any               `json:"pagesize,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type LongaudioAlbumAudiosResponse = Response

type LongaudioAlbumDetailRequest struct {
	AlbumId any               `json:"album_id,omitempty"`
	Cookie  map[string]string `json:"-"`
	Extra   map[string]any    `json:"-"`
}

type LongaudioAlbumDetailResponse = Response

type LongaudioDailyRecommendRequest struct {
	Page     any               `json:"page,omitempty"`
	Pagesize any               `json:"pagesize,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type LongaudioDailyRecommendResponse = Response

type LongaudioRankRecommendRequest struct {
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type LongaudioRankRecommendResponse = Response

type LongaudioVipRecommendRequest struct {
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type LongaudioVipRecommendResponse = Response

type LongaudioWeekRecommendRequest struct {
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type LongaudioWeekRecommendResponse = Response

type LyricRequest struct {
	Accesskey any               `json:"accesskey,omitempty"`
	Client    string            `json:"client,omitempty"`
	Decode    any               `json:"decode,omitempty"`
	Fmt       any               `json:"fmt,omitempty"`
	Id        any               `json:"id,omitempty"`
	Cookie    map[string]string `json:"-"`
	Extra     map[string]any    `json:"-"`
}

type LyricResponse Response

type PcDiantaiRequest struct {
	Userid int               `json:"userid,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type PcDiantaiResponse = Response

func (c *Client) PcDiantai(ctx context.Context, req PcDiantaiRequest) (*PcDiantaiResponse, error) {
	params := structToMap(req)
	delete(params, "Cookie")
	delete(params, "Extra")
	if compat, ok := buildCompatParams("pc_diantai", params, req.Cookie); ok {
		params = compat
	}
	for k, v := range req.Extra {
		params[k] = v
	}
	cookie := applyCompatCookie("pc_diantai", req.Cookie)
	resp, err := c.Call(ctx, RoutePcDiantai, Request{Params: params, Cookie: cookie})
	if err != nil {
		return nil, err
	}
	out := PcDiantaiResponse(*resp)
	return &out, nil
}
