// Code generated by tools/gen; DO NOT EDIT.
package sdk

func buildCompatParamsGroupB(identifier string, in map[string]any, cookie map[string]string) (map[string]any, bool) {
	switch identifier {
	case "comment_playlist":
		out := map[string]any{}
		out["need_show_image"] = 1
		out["code"] = "ca53b96fe5a1d9c22d71c8f522ef7c4f"
		out["content_type"] = 0
		out["tag"] = 5
		out["url"] = "/m.comment.service/v1/cmtlist"
		out["encryptType"] = "android"
		out["method"] = "POST"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "fm_class":
		out := map[string]any{}
		out["mid"] = cookie["KUGOU_API_MID"]
		out["platform"] = "android"
		out["get_tracker"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "fm_image":
		out := map[string]any{}
		out["mid"] = cookie["KUGOU_API_MID"]
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "fm_recommend":
		out := map[string]any{}
		out["mid"] = cookie["KUGOU_API_MID"]
		out["rcmdsongcount"] = 1
		out["level"] = 0
		out["area_code"] = 1
		out["get_tracker"] = 1
		out["uid"] = 0
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "fm_songs":
		out := map[string]any{}
		out["area_code"] = 1
		out["get_tracker"] = 1
		out["mid"] = cookie["KUGOU_API_MID"]
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "images":
		out := map[string]any{}
		out["album_image_type"] = "-3"
		out["author_image_type"] = "3,4,5"
		out["count"] = compatFirstAnyInt(in["count"], 5)
		out["isCdn"] = 1
		out["publish_time"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "images_audio":
		out := map[string]any{}
		out["count"] = compatFirstAnyInt(in["count"], 5)
		out["isCdn"] = 1
		out["publish_time"] = 1
		out["show_authors"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "ip":
		out := map[string]any{}
		out["is_publish"] = 1
		out["ip_id"] = in["id"]
		out["sort"] = 3
		out["page"] = compatFirstAnyInt(in["page"], 1)
		out["pagesize"] = compatFirstAnyInt(in["pagesize"], 30)
		out["query"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "ip_dateil":
		out := map[string]any{}
		out["is_publish"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "ip_playlist":
		out := map[string]any{}
		out["ip"] = in["id"]
		out["page"] = compatFirstAnyInt(in["page"], 1)
		out["pagesize"] = compatFirstAnyInt(in["pagesize"], 30)
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "ip_zone_home":
		out := map[string]any{}
		out["id"] = in["id"]
		out["share"] = 0
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "lastest_songs_listen":
		out := map[string]any{}
		out["area_code"] = "1"
		out["ret_info"] = 1
		out["url"] = "/playque/devque/v1/get_latest_songs"
		out["encryptType"] = "android"
		out["method"] = "POST"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "login":
		out := map[string]any{}
		out["plat"] = 1
		out["support_multi"] = 1
		out["t1"] = "562a6f12a6e803453647d16a08f5f0c2ff7eee692cba2ab74cc4c8ab47fc467561a7c6b586ce7dc46a63613b246737c03a1dc8f8d162d8ce1d2c71893d19f1d4b797685a4c6d3d81341cbde65e488c4829a9b4d42ef2df470eb102979fa5adcdd9b4eecfea8b909ff7599abeb49867640f10c3c70fc444effca9d15db44a9a6c907731e2bb0f22cd9b3536380169995693e5f0e2424e3378097d3813186e3fe96bbe7023808a0981b4e2b6135a76faac"
		out["t2"] = "31c4daf4cf480169ccea1cb7d4a209295865a9d2b788510301694db229b87807469ea0d41b4d4b9173c2151da7294aeebfc9738df154bbdf11a4e117bb5dff6a3af8ce5ce333e681c1f29a44038f27567d58992eb81283e080778ac77db1400fdf49b7cf7e26be2e5af4da7830cc3be4"
		out["t3"] = "MCwwLDAsMCwwLDAsMCwwLDA="
		out["username"] = in["username"]
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "login_device":
		out := map[string]any{}
		out["plat"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "login_openplat":
		out := map[string]any{}
		out["force_login"] = 1
		out["partnerid"] = 36
		out["t3"] = "MCwwLDAsMCwwLDAsMCwwLDA="
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "login_token":
		out := map[string]any{}
		out["plat"] = 1
		out["t3"] = "MCwwLDAsMCwwLDAsMCwwLDA="
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "lyric":
		out := map[string]any{}
		out["ver"] = 1
		out["client"] = compatFirstAnyString(in["client"], "android")
		out["id"] = in["id"]
		out["accesskey"] = in["accesskey"]
		out["charset"] = "utf8"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "pc_diantai":
		out := map[string]any{}
		out["isvip"] = 0
		out["vipType"] = 0
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	default:
		return nil, false
	}
}
