// Code generated by tools/gen; DO NOT EDIT.
package sdk

func buildCompatParamsGroupD(identifier string, in map[string]any, cookie map[string]string) (map[string]any, bool) {
	switch identifier {
	case "search_mixed":
		out := map[string]any{}
		out["ab_tag"] = 0
		out["ability"] = 511
		out["albumhide"] = 0
		out["apiver"] = 22
		out["area_code"] = 1
		out["clientver"] = 20125
		out["cursor"] = 0
		out["is_gpay"] = 0
		out["iscorrection"] = 1
		out["nocollect"] = 0
		out["platform"] = "IOSFilter"
		out["recver"] = 2
		out["req_ai"] = 1
		out["requestid"] = "${cryptoMd5(`bdaa53d04e7475feb9024164a47032f9${time}`)}_0"
		out["search_ability"] = 3
		out["sec_aggre"] = 1
		out["sec_aggre_bitmap"] = 0
		out["style_type"] = 3
		out["tag"] = "em"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "sheet_collection":
		out := map[string]any{}
		out["url"] = "/miniyueku/v1/opern_square/get_home_module_config"
		out["encryptType"] = "web"
		out["method"] = "GET"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "sheet_collection_detail":
		out := map[string]any{}
		out["url"] = "/miniyueku/v1/opern_square/collection_detail"
		out["encryptType"] = "web"
		out["method"] = "GET"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "sheet_detail":
		out := map[string]any{}
		out["baseURL"] = "https://miniyueku.kugou.com"
		out["url"] = "/v1/opern/detail"
		out["encryptType"] = "android"
		out["method"] = "GET"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "sheet_list":
		out := map[string]any{}
		out["url"] = "/miniyueku/v1/opern/list"
		out["encryptType"] = "android"
		out["method"] = "GET"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "song_url":
		out := map[string]any{}
		out["area_code"] = 1
		out["ssa_flag"] = "is_fromtrack"
		out["version"] = 11436
		out["behavior"] = "play"
		out["cmd"] = 26
		out["pidversion"] = 3001
		out["cdnBackup"] = 1
		out["kcard"] = 0
		out["module"] = ""
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "song_url_new":
		out := map[string]any{}
		out["area_code"] = "1"
		out["behavior"] = "play"
		out["collect_list_id"] = "3"
		out["id"] = 0
		out["page_id"] = 1
		out["type"] = "audio"
		out["all_m"] = 1
		out["auth"] = ""
		out["module_id"] = 0
		out["need_climax"] = 1
		out["need_xcdn"] = 1
		out["open_time"] = ""
		out["pid"] = "411"
		out["pidversion"] = "3001"
		out["priv_vip_type"] = "6"
		out["userid"] = "${userid}"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "theme_music":
		out := map[string]any{}
		out["platform"] = "android"
		out["show_theme_category_ids"] = in["ids"]
		out["userid"] = compatFirstAny(in["userid"], cookie["userid"], compatDefaultLiteral("int", "", 0, false))
		out["module_id"] = 508
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "theme_music_detail":
		out := map[string]any{}
		out["platform"] = "android"
		out["theme_category_id"] = in["id"]
		out["show_theme_category_id"] = 0
		out["userid"] = compatFirstAny(in["userid"], cookie["userid"], compatDefaultLiteral("int", "", 0, false))
		out["module_id"] = 508
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "theme_playlist":
		out := map[string]any{}
		out["platform"] = "android"
		out["area_code"] = 1
		out["module_id"] = 1
		out["userid"] = compatFirstAny(in["userid"], cookie["userid"], compatDefaultLiteral("int", "", 0, false))
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "theme_playlist_track":
		out := map[string]any{}
		out["platform"] = "android"
		out["area_code"] = 1
		out["module_id"] = 1
		out["userid"] = compatFirstAny(in["userid"], cookie["userid"], compatDefaultLiteral("int", "", 0, false))
		out["theme_id"] = in["theme_id"]
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "top_album":
		out := map[string]any{}
		out["token"] = compatFirstAny(in["token"], cookie["token"], compatDefaultLiteral("string", "", 0, false))
		out["page"] = compatFirstAnyInt(in["page"], 1)
		out["pagesize"] = compatFirstAnyInt(in["pagesize"], 30)
		out["withpriv"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "top_card":
		out := map[string]any{}
		out["platform"] = "android"
		out["userid"] = compatFirstAny(in["userid"], cookie["userid"], compatDefaultLiteral("int", "", 0, false))
		out["area_code"] = 1
		out["uuid"] = "-"
		out["u_info"] = "a0c35cd40af564444b5584c2754dedec"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "top_card_youth":
		out := map[string]any{}
		out["u_info"] = ""
		out["source_mixsong"] = ""
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "top_ip":
		out := map[string]any{}
		out["baseURL"] = "http://musicadservice.kugou.com"
		out["url"] = "/v1/daily_recommend"
		out["encryptType"] = "android"
		out["method"] = "POST"
		out["clientver"] = 12349
		out["area_code"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "top_playlist":
		out := map[string]any{}
		out["mid"] = cookie["KUGOU_API_MID"]
		out["platform"] = "android"
		out["userid"] = compatFirstAny(in["userid"], cookie["userid"], compatDefaultLiteral("int", "", 0, false))
		out["module_id"] = compatFirstAnyInt(in["module_id"], 1)
		out["page"] = compatFirstAnyInt(in["page"], 1)
		out["pagesize"] = compatFirstAnyInt(in["pagesize"], 30)
		out["req_multi"] = 1
		out["retrun_min"] = 5
		out["return_special_falg"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "top_song":
		out := map[string]any{}
		out["rank_id"] = compatFirstAnyInt(in["type"], 21608)
		out["userid"] = compatFirstAny(in["userid"], cookie["userid"], compatDefaultLiteral("int", "", 0, false))
		out["page"] = compatFirstAnyInt(in["page"], 1)
		out["pagesize"] = compatFirstAnyInt(in["pagesize"], 30)
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	default:
		return nil, false
	}
}
