// Code generated by tools/gen; DO NOT EDIT.
package sdk

import (
	"fmt"
	"strconv"
)

func buildCompatParams(identifier string, in map[string]any, cookie map[string]string) (map[string]any, bool) {
	switch identifier {
	case "ai_recommend":
		out := map[string]any{}
		out["platform"] = "ios"
		out["source_type"] = 2
		out["playlist_ver"] = 2
		out["area_code"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "album":
		out := map[string]any{}
		out["fields"] = compatFirstAnyString(in["fields"], "")
		out["mid"] = cookie["KUGOU_API_MID"]
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "album_songs":
		out := map[string]any{}
		out["is_buy"] = compatFirstAnyString(in["is_buy"], "")
		out["page"] = compatFirstAnyInt(in["page"], 1)
		out["pagesize"] = compatFirstAnyInt(in["pagesize"], 30)
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "artist_albums":
		out := map[string]any{}
		out["pagesize"] = compatFirstAnyInt(in["pagesize"], 30)
		out["page"] = compatFirstAnyInt(in["page"], 1)
		out["category"] = 1
		out["area_code"] = "all"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "artist_audios":
		out := map[string]any{}
		out["pagesize"] = compatFirstAnyInt(in["pagesize"], 30)
		out["page"] = compatFirstAnyInt(in["page"], 1)
		out["area_code"] = "all"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "artist_follow":
		out := map[string]any{}
		out["plat"] = 0
		out["source"] = 7
		out["url"] = "/followservice/v3/follow_singer"
		out["method"] = "post"
		out["encryptType"] = "android"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "artist_lists":
		out := map[string]any{}
		out["showtype"] = 2
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "artist_unfollow":
		out := map[string]any{}
		out["plat"] = 0
		out["source"] = 7
		out["url"] = "/followservice/v3/unfollow_singer"
		out["method"] = "post"
		out["encryptType"] = "android"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "artist_videos":
		out := map[string]any{}
		out["is_fanmade"] = ""
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "audio":
		out := map[string]any{}
		out["mid"] = cookie["KUGOU_API_MID"]
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "audio_accompany_matching":
		out := map[string]any{}
		out["isteen"] = 0
		out["usemkv"] = 1
		out["platform"] = 2
		out["version"] = 12375
		out["baseURL"] = "https://nsongacsing.kugou.com"
		out["url"] = "/sing7/accompanywan/json/v2/cdn/optimal_matching_accompany_2_listen.do"
		out["method"] = "get"
		out["encryptType"] = "android"
		out["clearDefaultParams"] = true
		out["notSignature"] = true
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "audio_ktv_total":
		out := map[string]any{}
		out["isteen"] = 0
		out["usemkv"] = 1
		out["platform"] = 2
		out["version"] = 12375
		out["baseURL"] = "https://acsing.service.kugou.com"
		out["url"] = "/sing7/listenguide/json/v2/cdn/listenguide/get_total_opus_num_v02.do"
		out["method"] = "get"
		out["encryptType"] = "android"
		out["clearDefaultParams"] = true
		out["notSignature"] = true
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "captcha_sent":
		out := map[string]any{}
		out["businessid"] = 5
		out["mobile"] = "${params?.mobile}"
		out["plat"] = 3
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "comment_album":
		out := map[string]any{}
		out["need_show_image"] = 1
		out["code"] = "94f1792ced1df89aa68a7939eaf2efca"
		out["url"] = "/m.comment.service/v1/cmtlist"
		out["encryptType"] = "android"
		out["method"] = "POST"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "comment_count":
		out := map[string]any{}
		out["r"] = "comments/getcommentsnum"
		out["code"] = "fc4be23b4e972707f36b8a828a93ba8a"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "comment_floor":
		out := map[string]any{}
		out["need_show_image"] = 1
		out["code"] = "fc4be23b4e972707f36b8a828a93ba8a"
		out["url"] = "/mcomment/v1/hot_replylist"
		out["encryptType"] = "android"
		out["method"] = "POST"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "comment_music":
		out := map[string]any{}
		out["need_show_image"] = 1
		out["extdata"] = "0"
		out["code"] = "fc4be23b4e972707f36b8a828a93ba8a"
		out["url"] = "/mcomment/v1/cmtlist"
		out["encryptType"] = "android"
		out["method"] = "POST"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "comment_music_classify":
		out := map[string]any{}
		out["need_show_image"] = 1
		out["extdata"] = "0"
		out["code"] = "fc4be23b4e972707f36b8a828a93ba8a"
		out["url"] = "/mcomment/v1/cmt_classify_list"
		out["encryptType"] = "android"
		out["method"] = "POST"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "comment_music_hotword":
		out := map[string]any{}
		out["need_show_image"] = 1
		out["extdata"] = "0"
		out["code"] = "fc4be23b4e972707f36b8a828a93ba8a"
		out["url"] = "/mcomment/v1/get_hot_word"
		out["encryptType"] = "android"
		out["method"] = "POST"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "comment_playlist":
		out := map[string]any{}
		out["need_show_image"] = 1
		out["code"] = "ca53b96fe5a1d9c22d71c8f522ef7c4f"
		out["content_type"] = 0
		out["tag"] = 5
		out["url"] = "/m.comment.service/v1/cmtlist"
		out["encryptType"] = "android"
		out["method"] = "POST"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "fm_class":
		out := map[string]any{}
		out["mid"] = cookie["KUGOU_API_MID"]
		out["platform"] = "android"
		out["get_tracker"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "fm_image":
		out := map[string]any{}
		out["mid"] = cookie["KUGOU_API_MID"]
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "fm_recommend":
		out := map[string]any{}
		out["mid"] = cookie["KUGOU_API_MID"]
		out["rcmdsongcount"] = 1
		out["level"] = 0
		out["area_code"] = 1
		out["get_tracker"] = 1
		out["uid"] = 0
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "fm_songs":
		out := map[string]any{}
		out["area_code"] = 1
		out["get_tracker"] = 1
		out["mid"] = cookie["KUGOU_API_MID"]
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "images":
		out := map[string]any{}
		out["album_image_type"] = "-3"
		out["author_image_type"] = "3,4,5"
		out["count"] = compatFirstAnyInt(in["count"], 5)
		out["isCdn"] = 1
		out["publish_time"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "images_audio":
		out := map[string]any{}
		out["count"] = compatFirstAnyInt(in["count"], 5)
		out["isCdn"] = 1
		out["publish_time"] = 1
		out["show_authors"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "ip":
		out := map[string]any{}
		out["is_publish"] = 1
		out["ip_id"] = in["id"]
		out["sort"] = 3
		out["page"] = compatFirstAnyInt(in["page"], 1)
		out["pagesize"] = compatFirstAnyInt(in["pagesize"], 30)
		out["query"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "ip_dateil":
		out := map[string]any{}
		out["is_publish"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "ip_playlist":
		out := map[string]any{}
		out["ip"] = in["id"]
		out["page"] = compatFirstAnyInt(in["page"], 1)
		out["pagesize"] = compatFirstAnyInt(in["pagesize"], 30)
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "ip_zone_home":
		out := map[string]any{}
		out["id"] = in["id"]
		out["share"] = 0
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "lastest_songs_listen":
		out := map[string]any{}
		out["area_code"] = "1"
		out["ret_info"] = 1
		out["url"] = "/playque/devque/v1/get_latest_songs"
		out["encryptType"] = "android"
		out["method"] = "POST"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "login":
		out := map[string]any{}
		out["plat"] = 1
		out["support_multi"] = 1
		out["t1"] = "562a6f12a6e803453647d16a08f5f0c2ff7eee692cba2ab74cc4c8ab47fc467561a7c6b586ce7dc46a63613b246737c03a1dc8f8d162d8ce1d2c71893d19f1d4b797685a4c6d3d81341cbde65e488c4829a9b4d42ef2df470eb102979fa5adcdd9b4eecfea8b909ff7599abeb49867640f10c3c70fc444effca9d15db44a9a6c907731e2bb0f22cd9b3536380169995693e5f0e2424e3378097d3813186e3fe96bbe7023808a0981b4e2b6135a76faac"
		out["t2"] = "31c4daf4cf480169ccea1cb7d4a209295865a9d2b788510301694db229b87807469ea0d41b4d4b9173c2151da7294aeebfc9738df154bbdf11a4e117bb5dff6a3af8ce5ce333e681c1f29a44038f27567d58992eb81283e080778ac77db1400fdf49b7cf7e26be2e5af4da7830cc3be4"
		out["t3"] = "MCwwLDAsMCwwLDAsMCwwLDA="
		out["username"] = in["username"]
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "login_device":
		out := map[string]any{}
		out["plat"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "login_openplat":
		out := map[string]any{}
		out["force_login"] = 1
		out["partnerid"] = 36
		out["t3"] = "MCwwLDAsMCwwLDAsMCwwLDA="
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "login_token":
		out := map[string]any{}
		out["plat"] = 1
		out["t3"] = "MCwwLDAsMCwwLDAsMCwwLDA="
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "lyric":
		out := map[string]any{}
		out["ver"] = 1
		out["client"] = compatFirstAnyString(in["client"], "android")
		out["id"] = in["id"]
		out["accesskey"] = in["accesskey"]
		out["charset"] = "utf8"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "pc_diantai":
		out := map[string]any{}
		out["isvip"] = 0
		out["vipType"] = 0
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "personal_fm":
		out := map[string]any{}
		out["mid"] = cookie["KUGOU_API_MID"]
		out["action"] = compatFirstAnyString(in["action"], "play")
		out["recommend_source_locked"] = 0
		out["callerid"] = 0
		out["m_type"] = 1
		out["platform"] = compatFirstAnyString(in["platform"], "ios")
		out["area_code"] = 1
		out["mode"] = compatFirstAnyString(in["mode"], "normal")
		out["fakem"] = "ca981cfc583a4c37f28d2d49000013c16a0a"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "playhistory_upload":
		out := map[string]any{}
		out["url"] = "/playhistory/v1/upload_songs"
		out["encryptType"] = "android"
		out["method"] = "POST"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "playlist_add":
		out := map[string]any{}
		out["total_ver"] = 0
		out["is_pri"] = 0
		out["from_shupinmv"] = 0
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "playlist_del":
		out := map[string]any{}
		out["total_ver"] = 0
		out["type"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "playlist_detail":
		out := map[string]any{}
		out["userid"] = compatFirstAny(in["userid"], cookie["userid"], compatDefaultLiteral("int", "", 0, false))
		out["token"] = compatFirstAny(in["token"], cookie["token"], compatDefaultLiteral("string", "", 0, false))
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "playlist_effect":
		out := map[string]any{}
		out["page"] = compatFirstAnyInt(in["page"], 1)
		out["pagesize"] = compatFirstAnyInt(in["pagesize"], 30)
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "playlist_similar":
		out := map[string]any{}
		out["userid"] = compatFirstAny(in["userid"], cookie["userid"], compatDefaultLiteral("int", "", 0, false))
		out["ugc"] = 1
		out["show_list"] = 1
		out["need_songs"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "playlist_tags":
		out := map[string]any{}
		out["tag_type"] = "collection"
		out["tag_id"] = 0
		out["source"] = 3
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "playlist_track_all":
		out := map[string]any{}
		out["area_code"] = 1
		out["plat"] = 1
		out["type"] = 1
		out["mode"] = 1
		out["personal_switch"] = 1
		out["extend_fields"] = "abtags,hot_cmt,popularization"
		out["global_collection_id"] = in["id"]
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "playlist_track_all_new":
		out := map[string]any{}
		out["area_code"] = 1
		out["show_relate_goods"] = 0
		out["allplatform"] = 1
		out["show_cover"] = 1
		out["type"] = 0
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "playlist_tracks_add":
		out := map[string]any{}
		out["list_ver"] = 0
		out["type"] = 0
		out["slow_upload"] = 1
		out["scene"] = "false;null"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "playlist_tracks_del":
		out := map[string]any{}
		out["type"] = 0
		out["list_ver"] = 0
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "privilege_lite":
		out := map[string]any{}
		out["area_code"] = 1
		out["behavior"] = "play"
		out["need_hash_offset"] = 1
		out["relate"] = 1
		out["support_verify"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "rank_audio":
		out := map[string]any{}
		out["show_portrait_mv"] = 1
		out["show_type_total"] = 1
		out["filter_original_remarks"] = 1
		out["area_code"] = 1
		out["type"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "recommend_songs":
		out := map[string]any{}
		out["platform"] = compatFirstAnyString(in["platform"], "android")
		out["userid"] = compatFirstAny(in["userid"], cookie["userid"], compatDefaultLiteral("string", "0", 0, false))
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "search":
		out := map[string]any{}
		out["albumhide"] = 0
		out["iscorrection"] = 1
		out["keyword"] = compatFirstAnyString(in["keywords"], "")
		out["nocollect"] = 0
		out["page"] = compatFirstAnyInt(in["page"], 1)
		out["pagesize"] = compatFirstAnyInt(in["pagesize"], 30)
		out["platform"] = "AndroidFilter"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "search_complex":
		out := map[string]any{}
		out["platform"] = "AndroidFilter"
		out["page"] = compatFirstAnyInt(in["page"], 1)
		out["pagesize"] = compatFirstAnyInt(in["pagesize"], 30)
		out["cursor"] = 0
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "search_default":
		out := map[string]any{}
		out["plat"] = 0
		out["tags"] = "{}"
		out["m_type"] = 0
		out["ability"] = "3"
		out["bitmap"] = 2
		out["mode"] = "normal"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "search_hot":
		out := map[string]any{}
		out["navid"] = 1
		out["plat"] = 2
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "search_lyric":
		out := map[string]any{}
		out["album_audio_id"] = compatFirstAnyInt(in["album_audio_id"], 0)
		out["duration"] = 0
		out["hash"] = compatFirstAnyString(in["hash"], "")
		out["keyword"] = compatFirstAnyString(in["keywords"], "")
		out["lrctxt"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "search_mixed":
		out := map[string]any{}
		out["ab_tag"] = 0
		out["ability"] = 511
		out["albumhide"] = 0
		out["apiver"] = 22
		out["area_code"] = 1
		out["clientver"] = 20125
		out["cursor"] = 0
		out["is_gpay"] = 0
		out["iscorrection"] = 1
		out["nocollect"] = 0
		out["platform"] = "IOSFilter"
		out["recver"] = 2
		out["req_ai"] = 1
		out["requestid"] = "${cryptoMd5(`bdaa53d04e7475feb9024164a47032f9${time}`)}_0"
		out["search_ability"] = 3
		out["sec_aggre"] = 1
		out["sec_aggre_bitmap"] = 0
		out["style_type"] = 3
		out["tag"] = "em"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "sheet_collection":
		out := map[string]any{}
		out["url"] = "/miniyueku/v1/opern_square/get_home_module_config"
		out["encryptType"] = "web"
		out["method"] = "GET"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "sheet_collection_detail":
		out := map[string]any{}
		out["url"] = "/miniyueku/v1/opern_square/collection_detail"
		out["encryptType"] = "web"
		out["method"] = "GET"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "sheet_detail":
		out := map[string]any{}
		out["baseURL"] = "https://miniyueku.kugou.com"
		out["url"] = "/v1/opern/detail"
		out["encryptType"] = "android"
		out["method"] = "GET"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "sheet_list":
		out := map[string]any{}
		out["url"] = "/miniyueku/v1/opern/list"
		out["encryptType"] = "android"
		out["method"] = "GET"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "song_url":
		out := map[string]any{}
		out["area_code"] = 1
		out["ssa_flag"] = "is_fromtrack"
		out["version"] = 11436
		out["behavior"] = "play"
		out["cmd"] = 26
		out["pidversion"] = 3001
		out["cdnBackup"] = 1
		out["kcard"] = 0
		out["module"] = ""
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "song_url_new":
		out := map[string]any{}
		out["area_code"] = "1"
		out["behavior"] = "play"
		out["collect_list_id"] = "3"
		out["id"] = 0
		out["page_id"] = 1
		out["type"] = "audio"
		out["all_m"] = 1
		out["auth"] = ""
		out["module_id"] = 0
		out["need_climax"] = 1
		out["need_xcdn"] = 1
		out["open_time"] = ""
		out["pid"] = "411"
		out["pidversion"] = "3001"
		out["priv_vip_type"] = "6"
		out["userid"] = "${userid}"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "theme_music":
		out := map[string]any{}
		out["platform"] = "android"
		out["show_theme_category_ids"] = in["ids"]
		out["userid"] = compatFirstAny(in["userid"], cookie["userid"], compatDefaultLiteral("int", "", 0, false))
		out["module_id"] = 508
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "theme_music_detail":
		out := map[string]any{}
		out["platform"] = "android"
		out["theme_category_id"] = in["id"]
		out["show_theme_category_id"] = 0
		out["userid"] = compatFirstAny(in["userid"], cookie["userid"], compatDefaultLiteral("int", "", 0, false))
		out["module_id"] = 508
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "theme_playlist":
		out := map[string]any{}
		out["platform"] = "android"
		out["area_code"] = 1
		out["module_id"] = 1
		out["userid"] = compatFirstAny(in["userid"], cookie["userid"], compatDefaultLiteral("int", "", 0, false))
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "theme_playlist_track":
		out := map[string]any{}
		out["platform"] = "android"
		out["area_code"] = 1
		out["module_id"] = 1
		out["userid"] = compatFirstAny(in["userid"], cookie["userid"], compatDefaultLiteral("int", "", 0, false))
		out["theme_id"] = in["theme_id"]
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "top_album":
		out := map[string]any{}
		out["token"] = compatFirstAny(in["token"], cookie["token"], compatDefaultLiteral("string", "", 0, false))
		out["page"] = compatFirstAnyInt(in["page"], 1)
		out["pagesize"] = compatFirstAnyInt(in["pagesize"], 30)
		out["withpriv"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "top_card":
		out := map[string]any{}
		out["platform"] = "android"
		out["userid"] = compatFirstAny(in["userid"], cookie["userid"], compatDefaultLiteral("int", "", 0, false))
		out["area_code"] = 1
		out["uuid"] = "-"
		out["u_info"] = "a0c35cd40af564444b5584c2754dedec"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "top_card_youth":
		out := map[string]any{}
		out["u_info"] = ""
		out["source_mixsong"] = ""
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "top_ip":
		out := map[string]any{}
		out["baseURL"] = "http://musicadservice.kugou.com"
		out["url"] = "/v1/daily_recommend"
		out["encryptType"] = "android"
		out["method"] = "POST"
		out["clientver"] = 12349
		out["area_code"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "top_playlist":
		out := map[string]any{}
		out["mid"] = cookie["KUGOU_API_MID"]
		out["platform"] = "android"
		out["userid"] = compatFirstAny(in["userid"], cookie["userid"], compatDefaultLiteral("int", "", 0, false))
		out["module_id"] = compatFirstAnyInt(in["module_id"], 1)
		out["page"] = compatFirstAnyInt(in["page"], 1)
		out["pagesize"] = compatFirstAnyInt(in["pagesize"], 30)
		out["req_multi"] = 1
		out["retrun_min"] = 5
		out["return_special_falg"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "top_song":
		out := map[string]any{}
		out["rank_id"] = compatFirstAnyInt(in["type"], 21608)
		out["userid"] = compatFirstAny(in["userid"], cookie["userid"], compatDefaultLiteral("int", "", 0, false))
		out["page"] = compatFirstAnyInt(in["page"], 1)
		out["pagesize"] = compatFirstAnyInt(in["pagesize"], 30)
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "user_cloud":
		out := map[string]any{}
		out["getkmr"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "user_cloud_url":
		out := map[string]any{}
		out["ssa_flag"] = "is_fromtrack"
		out["version"] = "20102"
		out["ssl"] = 0
		out["pid"] = 20026
		out["kv_id"] = 2
		out["bucket"] = "musicclound"
		out["with_res_tag"] = 0
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "user_detail":
		out := map[string]any{}
		out["usertype"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "user_follow":
		out := map[string]any{}
		out["merge"] = 2
		out["need_iden_type"] = 1
		out["ext_params"] = "k_pic,jumptype,singerid,score"
		out["type"] = 0
		out["id_type"] = 0
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "user_history":
		out := map[string]any{}
		out["url"] = "/playhistory/v1/get_songs"
		out["encryptType"] = "android"
		out["method"] = "POST"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "user_listen":
		out := map[string]any{}
		out["area_code"] = 1
		out["cover"] = 2
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "user_playlist":
		out := map[string]any{}
		out["total_ver"] = 979
		out["type"] = 2
		out["page"] = compatFirstAnyInt(in["page"], 1)
		out["pagesize"] = compatFirstAnyInt(in["pagesize"], 30)
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "user_video_love":
		out := map[string]any{}
		out["load_video_info"] = 1
		out["p"] = 1
		out["plat"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "video_detail":
		out := map[string]any{}
		out["show_resolution"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "video_privilege":
		out := map[string]any{}
		out["area_code"] = 1
		out["behavior"] = "play"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "video_url":
		out := map[string]any{}
		out["backupdomain"] = 1
		out["cmd"] = 123
		out["ext"] = "mp4"
		out["ismp3"] = 0
		out["pid"] = 1
		out["type"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "youth_channel_song":
		out := map[string]any{}
		out["is_filter"] = 0
		out["url"] = "/youth/api/channel/v1/channel_get_song_audit_passed"
		out["encryptType"] = "android"
		out["method"] = "get"
		out["cookie"] = in["cookie"]
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "youth_channel_song_detail":
		out := map[string]any{}
		out["url"] = "/youth/v2/post/get_song_detail"
		out["encryptType"] = "android"
		out["method"] = "get"
		out["cookie"] = in["cookie"]
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "youth_day_vip_upgrade":
		out := map[string]any{}
		out["ad_type"] = "1"
		out["url"] = "/youth/v1/listen_song/upgrade_vip_reward"
		out["encryptType"] = "android"
		out["method"] = "post"
		out["cookie"] = in["cookie"]
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "youth_listen_song":
		out := map[string]any{}
		out["mixsongid"] = compatFirstAnyInt(in["mixsongid"], 666075191)
		out["url"] = "/youth/v2/report/listen_song"
		out["method"] = "POST"
		out["encryptTyPe"] = "android"
		out["cookie"] = in["cookie"]
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "youth_union_vip":
		out := map[string]any{}
		out["busi_type"] = "concept"
		out["opt_product_types"] = "dvip,qvip"
		out["product_type"] = "svip"
		out["baseURL"] = "https://kugouvip.kugou.com"
		out["url"] = "/v1/get_union_vip"
		out["encryptType"] = "android"
		out["method"] = "get"
		out["cookie"] = in["cookie"]
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "youth_user_song":
		out := map[string]any{}
		out["filter_video"] = 0
		out["type"] = compatFirstAnyInt(in["type"], 0)
		out["is_filter"] = 0
		out["url"] = "/youth/v1/get_user_song_public"
		out["encryptType"] = "android"
		out["method"] = "get"
		out["cookie"] = in["cookie"]
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "youth_vip":
		out := map[string]any{}
		out["ad_id"] = 12307537187
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "yueku_banner":
		out := map[string]any{}
		out["plat"] = 0
		out["channel"] = 201
		out["operator"] = 7
		out["networktype"] = 2
		out["userid"] = compatFirstAny(in["userid"], cookie["userid"], compatDefaultLiteral("int", "", 0, false))
		out["vip_type"] = 0
		out["m_type"] = 0
		out["apiver"] = 5
		out["ability"] = 2
		out["mode"] = "normal"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	default:
		return in, false
	}
}

func applyCompatCookie(identifier string, cookie map[string]string) map[string]string {
	out := map[string]string{}
	for k, v := range cookie {
		out[k] = v
	}
	switch identifier {
	case "captcha_sent":
		if v := cookie["KUGOU_API_MID"]; v != "" {
			out["mid"] = v
		}
	}
	return out
}

func compatFirstAny(v ...any) any {
	for _, x := range v {
		switch vv := x.(type) {
		case nil:
			continue
		case string:
			if vv != "" {
				return vv
			}
		default:
			return x
		}
	}
	return nil
}

func compatFirstAnyString(v any, def string) string {
	if v == nil {
		return def
	}
	s := fmt.Sprintf("%v", v)
	if s == "" || s == "<nil>" {
		return def
	}
	return s
}

func compatFirstAnyInt(v any, def int) int {
	if v == nil {
		return def
	}
	s := fmt.Sprintf("%v", v)
	if s == "" || s == "<nil>" {
		return def
	}
	n, err := strconv.Atoi(s)
	if err != nil || n == 0 {
		return def
	}
	return n
}

func compatDefaultLiteral(kind string, s string, i int, b bool) any {
	switch kind {
	case "string":
		return s
	case "int":
		return i
	case "bool":
		return b
	default:
		return nil
	}
}
