// Code generated by tools/gen; DO NOT EDIT.
package sdk

// Yueku request and response models are split out to keep generated shards small.
type YuekuRequest struct {
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type YuekuResponse = Response

type YuekuBannerRequest struct {
	Userid any               `json:"userid,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type YuekuBannerResponse = Response

type YuekuFmRequest struct {
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type YuekuFmResponse = Response
