// Code generated by tools/gen; DO NOT EDIT.
package sdk

// Rank and scene models share this generated shard.
type RankAudioRequest struct {
	Page     any               `json:"page,omitempty"`
	Pagesize any               `json:"pagesize,omitempty"`
	RankCid  any               `json:"rank_cid,omitempty"`
	Rankid   any               `json:"rankid,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type RankAudioResponse = Response

type RankInfoRequest struct {
	AlbumImg any               `json:"album_img,omitempty"`
	RankCid  any               `json:"rank_cid,omitempty"`
	Rankid   any               `json:"rankid,omitempty"`
	Zone     any               `json:"zone,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type RankInfoResponse = Response

type RankListRequest struct {
	Withsong any               `json:"withsong,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type RankListResponse = Response

type RankTopRequest struct {
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type RankTopResponse = Response

type RankVolRequest struct {
	RankCid any               `json:"rank_cid,omitempty"`
	Rankid  any               `json:"rankid,omitempty"`
	Cookie  map[string]string `json:"-"`
	Extra   map[string]any    `json:"-"`
}

type RankVolResponse = Response

type RecommendSongsRequest struct {
	Platform string            `json:"platform,omitempty"`
	Userid   any               `json:"userid,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type RecommendSongsResponse = Response

type RegisterDevRequest struct {
	Accelerometer      any               `json:"accelerometer,omitempty"`
	AccelerometerValue string            `json:"accelerometerValue,omitempty"`
	AvailableRamSize   int               `json:"availableRamSize,omitempty"`
	AvailableRomSize   int               `json:"availableRomSize,omitempty"`
	AvailableSDSize    int               `json:"availableSDSize,omitempty"`
	BasebandVer        string            `json:"basebandVer,omitempty"`
	BatteryLevel       int               `json:"batteryLevel,omitempty"`
	BatteryStatus      int               `json:"batteryStatus,omitempty"`
	Brand              string            `json:"brand,omitempty"`
	BuildSerial        string            `json:"buildSerial,omitempty"`
	Device             string            `json:"device,omitempty"`
	Gravity            any               `json:"gravity,omitempty"`
	GravityValue       string            `json:"gravityValue,omitempty"`
	Gyroscope          any               `json:"gyroscope,omitempty"`
	GyroscopeValue     string            `json:"gyroscopeValue,omitempty"`
	Imei               any               `json:"imei,omitempty"`
	Imsi               string            `json:"imsi,omitempty"`
	Light              any               `json:"light,omitempty"`
	LightValue         string            `json:"lightValue,omitempty"`
	Magnetic           any               `json:"magnetic,omitempty"`
	MagneticValue      string            `json:"magneticValue,omitempty"`
	Manufacturer       string            `json:"manufacturer,omitempty"`
	Orientation        any               `json:"orientation,omitempty"`
	OrientationValue   string            `json:"orientationValue,omitempty"`
	Pressure           any               `json:"pressure,omitempty"`
	PressureValue      string            `json:"pressureValue,omitempty"`
	StepCounter        any               `json:"step_counter,omitempty"`
	StepCounterValue   string            `json:"step_counterValue,omitempty"`
	Temperature        any               `json:"temperature,omitempty"`
	TemperatureValue   string            `json:"temperatureValue,omitempty"`
	Token              any               `json:"token,omitempty"`
	Userid             any               `json:"userid,omitempty"`
	Uuid               any               `json:"uuid,omitempty"`
	Cookie             map[string]string `json:"-"`
	Extra              map[string]any    `json:"-"`
}

type RegisterDevResponse = Response

type SceneAudioListRequest struct {
	Id       any               `json:"id,omitempty"`
	ModuleId any               `json:"module_id,omitempty"`
	Page     any               `json:"page,omitempty"`
	Pagesize any               `json:"pagesize,omitempty"`
	Tag      any               `json:"tag,omitempty"`
	Token    any               `json:"token,omitempty"`
	Userid   any               `json:"userid,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type SceneAudioListResponse = Response

type SceneCollectionListRequest struct {
	Page     any               `json:"page,omitempty"`
	Pagesize any               `json:"pagesize,omitempty"`
	TagId    any               `json:"tag_id,omitempty"`
	Token    any               `json:"token,omitempty"`
	Userid   any               `json:"userid,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type SceneCollectionListResponse = Response

type SceneListsRequest struct {
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type SceneListsResponse = Response

type SceneListsV2Request struct {
	Id       any               `json:"id,omitempty"`
	Page     any               `json:"page,omitempty"`
	Pagesize any               `json:"pagesize,omitempty"`
	Sort     any               `json:"sort,omitempty"`
	Userid   any               `json:"userid,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type SceneListsV2Response = Response

type SceneModuleRequest struct {
	Id     any               `json:"id,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type SceneModuleResponse = Response

type SceneModuleInfoRequest struct {
	Id       any               `json:"id,omitempty"`
	ModuleId any               `json:"module_id,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type SceneModuleInfoResponse = Response

type SceneMusicRequest struct {
	Id       any               `json:"id,omitempty"`
	Page     any               `json:"page,omitempty"`
	Pagesize any               `json:"pagesize,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type SceneMusicResponse = Response

type SceneVideoListRequest struct {
	Page     any               `json:"page,omitempty"`
	Pagesize any               `json:"pagesize,omitempty"`
	TagId    any               `json:"tag_id,omitempty"`
	Token    any               `json:"token,omitempty"`
	Userid   any               `json:"userid,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type SceneVideoListResponse = Response
