// Code generated by tools/gen; DO NOT EDIT.
package sdk

import "context"

// Comment, everyday, FM, and image models stay in one generated shard.
type CommentAlbumRequest struct {
	Id              any               `json:"id,omitempty"`
	Page            any               `json:"page,omitempty"`
	Pagesize        any               `json:"pagesize,omitempty"`
	ShowClassify    any               `json:"show_classify,omitempty"`
	ShowHotwordList any               `json:"show_hotword_list,omitempty"`
	Cookie          map[string]string `json:"-"`
	Extra           map[string]any    `json:"-"`
}

type CommentAlbumResponse = Response

type CommentCountRequest struct {
	Hash      any               `json:"hash,omitempty"`
	SpecialId any               `json:"special_id,omitempty"`
	Cookie    map[string]string `json:"-"`
	Extra     map[string]any    `json:"-"`
}

type CommentCountResponse = Response

func (c *Client) CommentCount(ctx context.Context, req CommentCountRequest) (*CommentCountResponse, error) {
	params := structToMap(req)
	delete(params, "Cookie")
	delete(params, "Extra")
	if compat, ok := buildCompatParams("comment_count", params, req.Cookie); ok {
		params = compat
	}
	for k, v := range req.Extra {
		params[k] = v
	}
	cookie := applyCompatCookie("comment_count", req.Cookie)
	resp, err := c.Call(ctx, RouteCommentCount, Request{Params: params, Cookie: cookie})
	if err != nil {
		return nil, err
	}
	out := CommentCountResponse(*resp)
	return &out, nil
}

type CommentFloorRequest struct {
	Mixsongid       any               `json:"mixsongid,omitempty"`
	Page            any               `json:"page,omitempty"`
	Pagesize        any               `json:"pagesize,omitempty"`
	ShowClassify    any               `json:"show_classify,omitempty"`
	ShowHotwordList any               `json:"show_hotword_list,omitempty"`
	SpecialId       any               `json:"special_id,omitempty"`
	Tid             any               `json:"tid,omitempty"`
	Cookie          map[string]string `json:"-"`
	Extra           map[string]any    `json:"-"`
}

type CommentFloorResponse = Response

type CommentMusicRequest struct {
	Mixsongid       any               `json:"mixsongid,omitempty"`
	Page            any               `json:"page,omitempty"`
	Pagesize        any               `json:"pagesize,omitempty"`
	ShowClassify    any               `json:"show_classify,omitempty"`
	ShowHotwordList any               `json:"show_hotword_list,omitempty"`
	Cookie          map[string]string `json:"-"`
	Extra           map[string]any    `json:"-"`
}

type CommentMusicResponse = Response

type CommentMusicClassifyRequest struct {
	Mixsongid any               `json:"mixsongid,omitempty"`
	Page      any               `json:"page,omitempty"`
	Pagesize  any               `json:"pagesize,omitempty"`
	Sort      int               `json:"sort,omitempty"`
	TypeId    any               `json:"type_id,omitempty"`
	Cookie    map[string]string `json:"-"`
	Extra     map[string]any    `json:"-"`
}

type CommentMusicClassifyResponse = Response

type CommentMusicHotwordRequest struct {
	HotWord   any               `json:"hot_word,omitempty"`
	Mixsongid any               `json:"mixsongid,omitempty"`
	Page      any               `json:"page,omitempty"`
	Pagesize  any               `json:"pagesize,omitempty"`
	Cookie    map[string]string `json:"-"`
	Extra     map[string]any    `json:"-"`
}

type CommentMusicHotwordResponse = Response

type CommentPlaylistRequest struct {
	Id              any               `json:"id,omitempty"`
	Page            any               `json:"page,omitempty"`
	Pagesize        any               `json:"pagesize,omitempty"`
	ShowClassify    any               `json:"show_classify,omitempty"`
	ShowHotwordList any               `json:"show_hotword_list,omitempty"`
	Cookie          map[string]string `json:"-"`
	Extra           map[string]any    `json:"-"`
}

type CommentPlaylistResponse = Response

type EverydayFriendRequest struct {
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type EverydayFriendResponse = Response

type EverydayHistoryRequest struct {
	Date        any               `json:"date,omitempty"`
	HistoryName any               `json:"history_name,omitempty"`
	Mode        any               `json:"mode,omitempty"`
	Platform    any               `json:"platform,omitempty"`
	Cookie      map[string]string `json:"-"`
	Extra       map[string]any    `json:"-"`
}

type EverydayHistoryResponse = Response

type EverydayRecommendRequest struct {
	Platform any               `json:"platform,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type EverydayRecommendResponse = Response

type EverydayStyleRecommendRequest struct {
	Platform any               `json:"platform,omitempty"`
	Tagids   any               `json:"tagids,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type EverydayStyleRecommendResponse = Response

type FavoriteCountRequest struct {
	Mixsongids any               `json:"mixsongids,omitempty"`
	Cookie     map[string]string `json:"-"`
	Extra      map[string]any    `json:"-"`
}

type FavoriteCountResponse = Response

type FmClassRequest struct {
	Userid int               `json:"userid,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type FmClassResponse = Response

type FmImageRequest struct {
	Dfid   string            `json:"dfid,omitempty"`
	Fmid   string            `json:"fmid,omitempty"`
	Token  any               `json:"token,omitempty"`
	Userid any               `json:"userid,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type FmImageResponse = Response

type FmRecommendRequest struct {
	Dfid   string            `json:"dfid,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type FmRecommendResponse = Response

type FmSongsRequest struct {
	Fmid     string            `json:"fmid,omitempty"`
	Fmoffset string            `json:"fmoffset,omitempty"`
	Fmsize   string            `json:"fmsize,omitempty"`
	Fmtype   string            `json:"fmtype,omitempty"`
	Offset   any               `json:"offset,omitempty"`
	Size     int               `json:"size,omitempty"`
	Type     int               `json:"type,omitempty"`
	Userid   any               `json:"userid,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type FmSongsResponse = Response

type ImagesRequest struct {
	AlbumAudioId string            `json:"album_audio_id,omitempty"`
	AlbumId      string            `json:"album_id,omitempty"`
	Count        int               `json:"count,omitempty"`
	Hash         string            `json:"hash,omitempty"`
	Cookie       map[string]string `json:"-"`
	Extra        map[string]any    `json:"-"`
}

type ImagesResponse = Response

func (c *Client) Images(ctx context.Context, req ImagesRequest) (*ImagesResponse, error) {
	params := structToMap(req)
	delete(params, "Cookie")
	delete(params, "Extra")
	if compat, ok := buildCompatParams("images", params, req.Cookie); ok {
		params = compat
	}
	for k, v := range req.Extra {
		params[k] = v
	}
	cookie := applyCompatCookie("images", req.Cookie)
	resp, err := c.Call(ctx, RouteImages, Request{Params: params, Cookie: cookie})
	if err != nil {
		return nil, err
	}
	out := ImagesResponse(*resp)
	return &out, nil
}
