// Code generated by tools/gen; DO NOT EDIT.
package sdk

func buildCompatParamsGroupE(identifier string, in map[string]any, cookie map[string]string) (map[string]any, bool) {
	switch identifier {
	case "user_cloud":
		out := map[string]any{}
		out["getkmr"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "user_cloud_url":
		out := map[string]any{}
		out["ssa_flag"] = "is_fromtrack"
		out["version"] = "20102"
		out["ssl"] = 0
		out["pid"] = 20026
		out["kv_id"] = 2
		out["bucket"] = "musicclound"
		out["with_res_tag"] = 0
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "user_detail":
		out := map[string]any{}
		out["usertype"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "user_follow":
		out := map[string]any{}
		out["merge"] = 2
		out["need_iden_type"] = 1
		out["ext_params"] = "k_pic,jumptype,singerid,score"
		out["type"] = 0
		out["id_type"] = 0
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "user_history":
		out := map[string]any{}
		out["url"] = "/playhistory/v1/get_songs"
		out["encryptType"] = "android"
		out["method"] = "POST"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "user_listen":
		out := map[string]any{}
		out["area_code"] = 1
		out["cover"] = 2
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "user_playlist":
		out := map[string]any{}
		out["total_ver"] = 979
		out["type"] = 2
		out["page"] = compatFirstAnyInt(in["page"], 1)
		out["pagesize"] = compatFirstAnyInt(in["pagesize"], 30)
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "user_video_love":
		out := map[string]any{}
		out["load_video_info"] = 1
		out["p"] = 1
		out["plat"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "video_detail":
		out := map[string]any{}
		out["show_resolution"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "video_privilege":
		out := map[string]any{}
		out["area_code"] = 1
		out["behavior"] = "play"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "video_url":
		out := map[string]any{}
		out["backupdomain"] = 1
		out["cmd"] = 123
		out["ext"] = "mp4"
		out["ismp3"] = 0
		out["pid"] = 1
		out["type"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "youth_channel_song":
		out := map[string]any{}
		out["is_filter"] = 0
		out["url"] = "/youth/api/channel/v1/channel_get_song_audit_passed"
		out["encryptType"] = "android"
		out["method"] = "get"
		out["cookie"] = in["cookie"]
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "youth_channel_song_detail":
		out := map[string]any{}
		out["url"] = "/youth/v2/post/get_song_detail"
		out["encryptType"] = "android"
		out["method"] = "get"
		out["cookie"] = in["cookie"]
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "youth_day_vip_upgrade":
		out := map[string]any{}
		out["ad_type"] = "1"
		out["url"] = "/youth/v1/listen_song/upgrade_vip_reward"
		out["encryptType"] = "android"
		out["method"] = "post"
		out["cookie"] = in["cookie"]
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "youth_listen_song":
		out := map[string]any{}
		out["mixsongid"] = compatFirstAnyInt(in["mixsongid"], 666075191)
		out["url"] = "/youth/v2/report/listen_song"
		out["method"] = "POST"
		out["encryptTyPe"] = "android"
		out["cookie"] = in["cookie"]
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "youth_union_vip":
		out := map[string]any{}
		out["busi_type"] = "concept"
		out["opt_product_types"] = "dvip,qvip"
		out["product_type"] = "svip"
		out["baseURL"] = "https://kugouvip.kugou.com"
		out["url"] = "/v1/get_union_vip"
		out["encryptType"] = "android"
		out["method"] = "get"
		out["cookie"] = in["cookie"]
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "youth_user_song":
		out := map[string]any{}
		out["filter_video"] = 0
		out["type"] = compatFirstAnyInt(in["type"], 0)
		out["is_filter"] = 0
		out["url"] = "/youth/v1/get_user_song_public"
		out["encryptType"] = "android"
		out["method"] = "get"
		out["cookie"] = in["cookie"]
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "youth_vip":
		out := map[string]any{}
		out["ad_id"] = 12307537187
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "yueku_banner":
		out := map[string]any{}
		out["plat"] = 0
		out["channel"] = 201
		out["operator"] = 7
		out["networktype"] = 2
		out["userid"] = compatFirstAny(in["userid"], cookie["userid"], compatDefaultLiteral("int", "", 0, false))
		out["vip_type"] = 0
		out["m_type"] = 0
		out["apiver"] = 5
		out["ability"] = 2
		out["mode"] = "normal"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	default:
		return nil, false
	}
}
