// Code generated by tools/gen; DO NOT EDIT.
package sdk

import "context"

// Generated login flow wrappers remain isolated for easier review.
type LoginRequest struct {
	Password string            `json:"password,omitempty"`
	Username any               `json:"username,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type LoginResponse = Response

func (c *Client) Login(ctx context.Context, req LoginRequest) (*LoginResponse, error) {
	params := structToMap(req)
	delete(params, "Cookie")
	delete(params, "Extra")
	if compat, ok := buildCompatParams("login", params, req.Cookie); ok {
		params = compat
	}
	for k, v := range req.Extra {
		params[k] = v
	}
	cookie := applyCompatCookie("login", req.Cookie)
	resp, err := c.Call(ctx, RouteLogin, Request{Params: params, Cookie: cookie})
	if err != nil {
		return nil, err
	}
	out := LoginResponse(*resp)
	return &out, nil
}

type LoginCellphoneRequest struct {
	Code   string            `json:"code,omitempty"`
	Mobile string            `json:"mobile,omitempty"`
	Userid any               `json:"userid,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type LoginCellphoneResponse = Response

func (c *Client) LoginCellphone(ctx context.Context, req LoginCellphoneRequest) (*LoginCellphoneResponse, error) {
	params := structToMap(req)
	delete(params, "Cookie")
	delete(params, "Extra")
	if compat, ok := buildCompatParams("login_cellphone", params, req.Cookie); ok {
		params = compat
	}
	for k, v := range req.Extra {
		params[k] = v
	}
	cookie := applyCompatCookie("login_cellphone", req.Cookie)
	resp, err := c.Call(ctx, RouteLoginCellphone, Request{Params: params, Cookie: cookie})
	if err != nil {
		return nil, err
	}
	out := LoginCellphoneResponse(*resp)
	return &out, nil
}

type LoginDeviceRequest struct {
	Token  any               `json:"token,omitempty"`
	Userid any               `json:"userid,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type LoginDeviceResponse = Response

func (c *Client) LoginDevice(ctx context.Context, req LoginDeviceRequest) (*LoginDeviceResponse, error) {
	params := structToMap(req)
	delete(params, "Cookie")
	delete(params, "Extra")
	if compat, ok := buildCompatParams("login_device", params, req.Cookie); ok {
		params = compat
	}
	for k, v := range req.Extra {
		params[k] = v
	}
	cookie := applyCompatCookie("login_device", req.Cookie)
	resp, err := c.Call(ctx, RouteLoginDevice, Request{Params: params, Cookie: cookie})
	if err != nil {
		return nil, err
	}
	out := LoginDeviceResponse(*resp)
	return &out, nil
}

type LoginOpenplatRequest struct {
	Code   string            `json:"code,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type LoginOpenplatResponse = Response

func (c *Client) LoginOpenplat(ctx context.Context, req LoginOpenplatRequest) (*LoginOpenplatResponse, error) {
	params := structToMap(req)
	delete(params, "Cookie")
	delete(params, "Extra")
	if compat, ok := buildCompatParams("login_openplat", params, req.Cookie); ok {
		params = compat
	}
	for k, v := range req.Extra {
		params[k] = v
	}
	cookie := applyCompatCookie("login_openplat", req.Cookie)
	resp, err := c.Call(ctx, RouteLoginOpenplat, Request{Params: params, Cookie: cookie})
	if err != nil {
		return nil, err
	}
	out := LoginOpenplatResponse(*resp)
	return &out, nil
}

type LoginQrCheckRequest struct {
	Key    any               `json:"key,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type LoginQrCheckResponse = Response

func (c *Client) LoginQrCheck(ctx context.Context, req LoginQrCheckRequest) (*LoginQrCheckResponse, error) {
	params := structToMap(req)
	delete(params, "Cookie")
	delete(params, "Extra")
	if compat, ok := buildCompatParams("login_qr_check", params, req.Cookie); ok {
		params = compat
	}
	for k, v := range req.Extra {
		params[k] = v
	}
	cookie := applyCompatCookie("login_qr_check", req.Cookie)
	resp, err := c.Call(ctx, RouteLoginQrCheck, Request{Params: params, Cookie: cookie})
	if err != nil {
		return nil, err
	}
	out := LoginQrCheckResponse(*resp)
	return &out, nil
}

type LoginQrCreateRequest struct {
	Key    any               `json:"key,omitempty"`
	Qrimg  any               `json:"qrimg,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type LoginQrCreateResponse = Response

func (c *Client) LoginQrCreate(ctx context.Context, req LoginQrCreateRequest) (*LoginQrCreateResponse, error) {
	params := structToMap(req)
	delete(params, "Cookie")
	delete(params, "Extra")
	if compat, ok := buildCompatParams("login_qr_create", params, req.Cookie); ok {
		params = compat
	}
	for k, v := range req.Extra {
		params[k] = v
	}
	cookie := applyCompatCookie("login_qr_create", req.Cookie)
	resp, err := c.Call(ctx, RouteLoginQrCreate, Request{Params: params, Cookie: cookie})
	if err != nil {
		return nil, err
	}
	out := LoginQrCreateResponse(*resp)
	return &out, nil
}
