// Code generated by tools/gen; DO NOT EDIT.
package sdk

import "context"

// Media discovery request and response models are grouped here.
type AiRecommendRequest struct {
	AlbumAudioId string            `json:"album_audio_id,omitempty"`
	Userid       any               `json:"userid,omitempty"`
	Cookie       map[string]string `json:"-"`
	Extra        map[string]any    `json:"-"`
}

type AiRecommendResponse = Response

type AlbumRequest struct {
	AlbumId string            `json:"album_id,omitempty"`
	Dfid    string            `json:"dfid,omitempty"`
	Fields  string            `json:"fields,omitempty"`
	Token   int               `json:"token,omitempty"`
	Userid  int               `json:"userid,omitempty"`
	Cookie  map[string]string `json:"-"`
	Extra   map[string]any    `json:"-"`
}

type AlbumResponse = Response

type AlbumDetailRequest struct {
	Id     any               `json:"id,omitempty"`
	IsBuy  int               `json:"is_buy,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type AlbumDetailResponse = Response

type AlbumShopRequest struct {
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type AlbumShopResponse = Response

type AlbumSongsRequest struct {
	Id       any               `json:"id,omitempty"`
	IsBuy    string            `json:"is_buy,omitempty"`
	Page     int               `json:"page,omitempty"`
	Pagesize int               `json:"pagesize,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type AlbumSongsResponse = Response

type ArtistAlbumsRequest struct {
	Id       any               `json:"id,omitempty"`
	Page     int               `json:"page,omitempty"`
	Pagesize int               `json:"pagesize,omitempty"`
	Sort     any               `json:"sort,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type ArtistAlbumsResponse = Response

type ArtistAudiosRequest struct {
	Id       any               `json:"id,omitempty"`
	Page     int               `json:"page,omitempty"`
	Pagesize int               `json:"pagesize,omitempty"`
	Sort     any               `json:"sort,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type ArtistAudiosResponse = Response

type ArtistDetailRequest struct {
	Id     any               `json:"id,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type ArtistDetailResponse = Response

type ArtistFollowRequest struct {
	Id     int               `json:"id,omitempty"`
	Token  any               `json:"token,omitempty"`
	Userid int               `json:"userid,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type ArtistFollowResponse = Response

type ArtistFollowNewsongsRequest struct {
	LastAlbumId any               `json:"last_album_id,omitempty"`
	OptSort     any               `json:"opt_sort,omitempty"`
	Pagesize    any               `json:"pagesize,omitempty"`
	Cookie      map[string]string `json:"-"`
	Extra       map[string]any    `json:"-"`
}

type ArtistFollowNewsongsResponse = Response

type ArtistHonourRequest struct {
	Id       any               `json:"id,omitempty"`
	Page     int               `json:"page,omitempty"`
	Pagesize int               `json:"pagesize,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type ArtistHonourResponse = Response

type ArtistListsRequest struct {
	Hotsize  int               `json:"hotsize,omitempty"`
	Musician int               `json:"musician,omitempty"`
	Sextypes any               `json:"sextypes,omitempty"`
	Type     any               `json:"type,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type ArtistListsResponse = Response

type ArtistUnfollowRequest struct {
	Id     any               `json:"id,omitempty"`
	Token  any               `json:"token,omitempty"`
	Userid any               `json:"userid,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type ArtistUnfollowResponse = Response

type ArtistVideosRequest struct {
	Id       any               `json:"id,omitempty"`
	Page     any               `json:"page,omitempty"`
	Pagesize any               `json:"pagesize,omitempty"`
	Tag      string            `json:"tag,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type ArtistVideosResponse = Response

type AudioRequest struct {
	Dfid   string            `json:"dfid,omitempty"`
	Hash   string            `json:"hash,omitempty"`
	Token  int               `json:"token,omitempty"`
	Userid int               `json:"userid,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type AudioResponse = Response

type AudioAccompanyMatchingRequest struct {
	FileName any               `json:"fileName,omitempty"`
	Hash     any               `json:"hash,omitempty"`
	MixId    int               `json:"mixId,omitempty"`
	Cookie   map[string]string `json:"-"`
	Extra    map[string]any    `json:"-"`
}

type AudioAccompanyMatchingResponse = Response

type AudioKtvTotalRequest struct {
	SingerName any               `json:"singerName,omitempty"`
	SongHash   any               `json:"songHash,omitempty"`
	SongId     int               `json:"songId,omitempty"`
	Cookie     map[string]string `json:"-"`
	Extra      map[string]any    `json:"-"`
}

type AudioKtvTotalResponse = Response

type AudioRelatedRequest struct {
	AlbumAudioId int               `json:"album_audio_id,omitempty"`
	Page         any               `json:"page,omitempty"`
	Pagesize     any               `json:"pagesize,omitempty"`
	ShowDetail   int               `json:"show_detail,omitempty"`
	ShowType     any               `json:"show_type,omitempty"`
	Sort         any               `json:"sort,omitempty"`
	Type         any               `json:"type,omitempty"`
	Cookie       map[string]string `json:"-"`
	Extra        map[string]any    `json:"-"`
}

type AudioRelatedResponse = Response

type BrushRequest struct {
	Mode       string            `json:"mode,omitempty"`
	SongPoolId int               `json:"song_pool_id,omitempty"`
	Userid     int               `json:"userid,omitempty"`
	VipType    int               `json:"vipType,omitempty"`
	Cookie     map[string]string `json:"-"`
	Extra      map[string]any    `json:"-"`
}

type BrushResponse = Response

type CaptchaSentRequest struct {
	Mobile any               `json:"mobile,omitempty"`
	Cookie map[string]string `json:"-"`
	Extra  map[string]any    `json:"-"`
}

type CaptchaSentResponse = Response

func (c *Client) CaptchaSent(ctx context.Context, req CaptchaSentRequest) (*CaptchaSentResponse, error) {
	params := structToMap(req)
	delete(params, "Cookie")
	delete(params, "Extra")
	if compat, ok := buildCompatParams("captcha_sent", params, req.Cookie); ok {
		params = compat
	}
	for k, v := range req.Extra {
		params[k] = v
	}
	cookie := applyCompatCookie("captcha_sent", req.Cookie)
	resp, err := c.Call(ctx, RouteCaptchaSent, Request{Params: params, Cookie: cookie})
	if err != nil {
		return nil, err
	}
	out := CaptchaSentResponse(*resp)
	return &out, nil
}
