// Code generated by tools/gen; DO NOT EDIT.
package sdk

func buildCompatParamsGroupA(identifier string, in map[string]any, cookie map[string]string) (map[string]any, bool) {
	switch identifier {
	case "ai_recommend":
		out := map[string]any{}
		out["platform"] = "ios"
		out["source_type"] = 2
		out["playlist_ver"] = 2
		out["area_code"] = 1
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "album":
		out := map[string]any{}
		out["fields"] = compatFirstAnyString(in["fields"], "")
		out["mid"] = cookie["KUGOU_API_MID"]
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "album_songs":
		out := map[string]any{}
		out["is_buy"] = compatFirstAnyString(in["is_buy"], "")
		out["page"] = compatFirstAnyInt(in["page"], 1)
		out["pagesize"] = compatFirstAnyInt(in["pagesize"], 30)
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "artist_albums":
		out := map[string]any{}
		out["pagesize"] = compatFirstAnyInt(in["pagesize"], 30)
		out["page"] = compatFirstAnyInt(in["page"], 1)
		out["category"] = 1
		out["area_code"] = "all"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "artist_audios":
		out := map[string]any{}
		out["pagesize"] = compatFirstAnyInt(in["pagesize"], 30)
		out["page"] = compatFirstAnyInt(in["page"], 1)
		out["area_code"] = "all"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "artist_follow":
		out := map[string]any{}
		out["plat"] = 0
		out["source"] = 7
		out["url"] = "/followservice/v3/follow_singer"
		out["method"] = "post"
		out["encryptType"] = "android"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "artist_lists":
		out := map[string]any{}
		out["showtype"] = 2
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "artist_unfollow":
		out := map[string]any{}
		out["plat"] = 0
		out["source"] = 7
		out["url"] = "/followservice/v3/unfollow_singer"
		out["method"] = "post"
		out["encryptType"] = "android"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "artist_videos":
		out := map[string]any{}
		out["is_fanmade"] = ""
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "audio":
		out := map[string]any{}
		out["mid"] = cookie["KUGOU_API_MID"]
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "audio_accompany_matching":
		out := map[string]any{}
		out["isteen"] = 0
		out["usemkv"] = 1
		out["platform"] = 2
		out["version"] = 12375
		out["baseURL"] = "https://nsongacsing.kugou.com"
		out["url"] = "/sing7/accompanywan/json/v2/cdn/optimal_matching_accompany_2_listen.do"
		out["method"] = "get"
		out["encryptType"] = "android"
		out["clearDefaultParams"] = true
		out["notSignature"] = true
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "audio_ktv_total":
		out := map[string]any{}
		out["isteen"] = 0
		out["usemkv"] = 1
		out["platform"] = 2
		out["version"] = 12375
		out["baseURL"] = "https://acsing.service.kugou.com"
		out["url"] = "/sing7/listenguide/json/v2/cdn/listenguide/get_total_opus_num_v02.do"
		out["method"] = "get"
		out["encryptType"] = "android"
		out["clearDefaultParams"] = true
		out["notSignature"] = true
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "captcha_sent":
		out := map[string]any{}
		out["businessid"] = 5
		out["mobile"] = "${params?.mobile}"
		out["plat"] = 3
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "comment_album":
		out := map[string]any{}
		out["need_show_image"] = 1
		out["code"] = "94f1792ced1df89aa68a7939eaf2efca"
		out["url"] = "/m.comment.service/v1/cmtlist"
		out["encryptType"] = "android"
		out["method"] = "POST"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "comment_count":
		out := map[string]any{}
		out["r"] = "comments/getcommentsnum"
		out["code"] = "fc4be23b4e972707f36b8a828a93ba8a"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "comment_floor":
		out := map[string]any{}
		out["need_show_image"] = 1
		out["code"] = "fc4be23b4e972707f36b8a828a93ba8a"
		out["url"] = "/mcomment/v1/hot_replylist"
		out["encryptType"] = "android"
		out["method"] = "POST"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "comment_music":
		out := map[string]any{}
		out["need_show_image"] = 1
		out["extdata"] = "0"
		out["code"] = "fc4be23b4e972707f36b8a828a93ba8a"
		out["url"] = "/mcomment/v1/cmtlist"
		out["encryptType"] = "android"
		out["method"] = "POST"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "comment_music_classify":
		out := map[string]any{}
		out["need_show_image"] = 1
		out["extdata"] = "0"
		out["code"] = "fc4be23b4e972707f36b8a828a93ba8a"
		out["url"] = "/mcomment/v1/cmt_classify_list"
		out["encryptType"] = "android"
		out["method"] = "POST"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	case "comment_music_hotword":
		out := map[string]any{}
		out["need_show_image"] = 1
		out["extdata"] = "0"
		out["code"] = "fc4be23b4e972707f36b8a828a93ba8a"
		out["url"] = "/mcomment/v1/get_hot_word"
		out["encryptType"] = "android"
		out["method"] = "POST"
		for k, v := range in {
			if _, ok := out[k]; !ok {
				out[k] = v
			}
		}
		return out, true
	default:
		return nil, false
	}
}
